"""
System Dashboard and Structural Integrity

The dashboard is the primary structural integrity check (Principle 8):
"The code is the constitution's test bench." If the dashboard shows green,
the system is coherent. If any indicator shows red, the papers have a
problem, not the code.

Structure:
  5.1  Condition monitors (I–IV) — foundational structural conditions
  5.2  EOH health indicators — deferred maintenance, compounding, registration
  5.3  Fiscal health — trust solvency, purchasing power trend, levy sufficiency

All four conditions must be GREEN for the system to be healthy. EOH health
and fiscal health provide early-warning YELLOW states before structural failure.

Colors:
  GREEN:  Condition passes; indicator within normal range.
  YELLOW: Condition passes but indicator approaching warning boundary.
  RED:    Condition fails or indicator in crisis range.

Mission Statement: §"Principle 8 — The code is the constitution's test bench";
§"Structural Conditions I–IV"; §"Deferred maintenance ratio"; §"Trust solvency";
§"Principle 5 — The floor rises with automation; it never falls"
"""

from __future__ import annotations
import math

from hours_eoh.data import (
    CARE_SIGMOID_DEFAULTS,
    COMPETENCY_THRESHOLD,
    CONTESTABILITY_CHI_CRIT,
    CONTESTABILITY_CHI_WARN,
    DEFAULT_SEGMENTS,
    M_BAND_LOW,
    M_BAND_HIGH,
    SUFF_LEVY_RATE,
    DEP_RATE,
    DIV_RATE,
    MEANINGFUL_ACTIVITY_TEH_BASE,
    DEFERRED_RATIO_WARN,
    DEFERRED_RATIO_CRIT,
    REGISTRATION_WARN,
    REGISTRATION_CRIT,
    COMPOUNDING_WARN,
    COMPOUNDING_CRIT,
    PP_INDEX_WARN,
    PP_INDEX_WARN_SLOPE,
    LEVY_SUFFICIENCY_WARN,
    CARE_ADMISSION_GREEN_FRAC,
    CARE_ADMISSION_YELLOW_FRAC,
)
from hours_eoh.core.conditions import (
    condition_i_check,
    condition_ii_check,
    balance_check,
    condition_iv_check,
)
from hours_eoh.core.multipliers import population_weighted_mean_multiplier
from hours_eoh.core.registration import (
    care_registration_share,
    total_registration_share,
    personal_eoh_registration_share,
)
from hours_eoh.core.eoh_dynamics import eoh_compounding
from hours_eoh.core.fiscal import (
    levy_collection,
    stewardship_allocation,
    ecological_allocation,
    sufficiency_guarantee,
    trust_management,
)
from hours_eoh.core.prices import floor_purchasing_power
from hours_eoh.core.workforce import competency_reserve, competency_check


# Thresholds are imported from data.py (single source of truth shared with stress.py).

# ---------------------------------------------------------------------------
# EOH Health Indicators
# ---------------------------------------------------------------------------

def eoh_health_indicators(
    total_eoh: float,
    fulfilled_eoh: float,
    epsilon: float = 0.40,
    deferred_eoh: float = 0.0,
    asset_type: str = "generic_infra",
    time_deferred: float = 0.0,
    registration_share: float | None = None,
) -> dict:
    """
    Phase 5.2: EOH health indicators for the current automation level.

    Measures four aspects of EOH system health:
    1. Deferred maintenance ratio: accumulated deferred EOH / total EOH.
       A rising ratio signals growing maintenance debt — compounding risk.
    2. EOH compounding rate: how much additional EOH the deferred backlog
       is generating. Threshold spike behavior (from Phase 2 eoh_dynamics).
    3. Registration coverage: what share of total EOH is in the collective
       ledger. Should rise with ε as care and stewardship registration grows.
    4. Care admission position: where the collective is on the care sigmoid.
       Should pace with ε — if lagging, human capital pipeline degrades.

    Args:
        total_eoh: Total EOH demand this period (all four domains).
        fulfilled_eoh: EOH actually fulfilled this period.
        epsilon: Automation level.
        deferred_eoh: Accumulated unfulfilled EOH from prior periods.
        asset_type: Asset type used for compounding profile. Default: "generic_infra".
        time_deferred: Years the current backlog has been accumulating.
        registration_share: Override for registration coverage [0,1].
                            If None, computed from total_registration_share(ε).

    Returns:
        dict: {
          "deferred_maintenance_ratio": float,    (deferred / total)
          "deferred_ratio_status":      str,      ("GREEN"/"YELLOW"/"RED")
          "eoh_compounding_amount":     float,    (extra EOH generated by backlog)
          "eoh_compounding_ratio":      float,    (compounding / deferred)
          "compounding_status":         str,
          "registration_coverage":      float,    (fraction in collective ledger)
          "registration_status":        str,
          "care_admission_share":       float,    (care sigmoid value at ε)
          "care_admission_status":      str,
          "fulfillment_rate":           float,    (fulfilled / total)
          "epsilon":                    float,
        }

    Reference: Mission Statement §"Deferred maintenance ratio"; §"EOH
    compounding — long slow accumulation, sharp threshold spike"
    """
    # 1. Deferred maintenance ratio
    deferred_ratio = deferred_eoh / max(total_eoh, 1.0)
    if deferred_ratio < DEFERRED_RATIO_WARN:
        deferred_status = "GREEN"
    elif deferred_ratio < DEFERRED_RATIO_CRIT:
        deferred_status = "YELLOW"
    else:
        deferred_status = "RED"

    # 2. EOH compounding (from Phase 2)
    if deferred_eoh > 0 and time_deferred > 0:
        compounding_amount = eoh_compounding(deferred_eoh, asset_type,
                                             time_deferred, epsilon)
        compounding_ratio = compounding_amount / max(deferred_eoh, 1.0)
    else:
        compounding_amount = 0.0
        compounding_ratio  = 0.0

    if compounding_ratio < COMPOUNDING_WARN:
        compounding_status = "GREEN"
    elif compounding_ratio < COMPOUNDING_CRIT:
        compounding_status = "YELLOW"
    else:
        compounding_status = "RED"

    # 3. Registration coverage
    if registration_share is None:
        registration_share = total_registration_share(epsilon)
    if epsilon < 0.10:
        # Subsistence bootstrapping: below the production sigmoid inflection (ε=0.10),
        # low registration is expected and healthy — the formal economy is intentionally tiny.
        reg_status = "GREEN"
    elif registration_share >= REGISTRATION_WARN:
        reg_status = "GREEN"
    elif registration_share >= REGISTRATION_CRIT:
        reg_status = "YELLOW"
    else:
        reg_status = "RED"

    # 4. Care admission position (sigmoid: where on the curve?)
    care_share = care_registration_share(epsilon)
    # Before the inflection point (ε=0.45), low care share is expected and healthy.
    # After the inflection, care share should be rising toward saturation.
    # RED/YELLOW only fire at high ε if care share is dramatically below the
    # sigmoid's own prediction — indicating an externally-modeled lag.
    # (Explicit lag testing is in care_registration_delay stress scenario.)
    _saturation = CARE_SIGMOID_DEFAULTS["saturation"]
    if epsilon < 0.45:
        care_status = "GREEN"  # early automation: low care share is expected
    elif care_share >= _saturation * CARE_ADMISSION_GREEN_FRAC:
        care_status = "GREEN"  # adequately progressed up the sigmoid
    elif care_share >= _saturation * CARE_ADMISSION_YELLOW_FRAC:
        care_status = "YELLOW"
    else:
        care_status = "RED"   # severely lagging at high ε

    fulfillment_rate = fulfilled_eoh / max(total_eoh, 1.0)

    # new-4: Personal EOH registration indicator.
    # At ε=0, personal EOH is entirely private (off-ledger). Rising share means
    # more of the population's biological obligations are collectively recognized
    # and funded — a key signal of the personal-to-collective ledger transition.
    pers_reg_share = personal_eoh_registration_share(epsilon)
    # Status mirrors non-personal registration thresholds
    if pers_reg_share >= REGISTRATION_WARN:
        pers_reg_status = "GREEN"
    elif pers_reg_share >= REGISTRATION_CRIT:
        pers_reg_status = "YELLOW"
    else:
        pers_reg_status = "RED"

    return {
        "deferred_maintenance_ratio":  deferred_ratio,
        "deferred_ratio_status":       deferred_status,
        "eoh_compounding_amount":      compounding_amount,
        "eoh_compounding_ratio":       compounding_ratio,
        "compounding_status":          compounding_status,
        "registration_coverage":       registration_share,
        "registration_status":         reg_status,
        "personal_registration_share": pers_reg_share,
        "personal_registration_status": pers_reg_status,
        "care_admission_share":        care_share,
        "care_admission_status":       care_status,
        "fulfillment_rate":            fulfillment_rate,
        "epsilon":                     epsilon,
    }


# ---------------------------------------------------------------------------
# Fiscal Health
# ---------------------------------------------------------------------------

def fiscal_health_check(
    trust_balance: float,
    labor_income: float,
    capital_stock_teh: float,
    capital_age_ratio: float,
    population: float,
    floor_teh: float,
    epsilon: float = 0.40,
    suff_levy_rate: float = SUFF_LEVY_RATE,
    dep_rate: float = DEP_RATE,
    div_rate: float = DIV_RATE,
    baseline_basket_cost: float = MEANINGFUL_ACTIVITY_TEH_BASE,
    ecosystem_health: float = 0.70,
    deferred_ecological: float = 0.0,
    eco_eoh_override: float | None = None,
    capital_eoh_eliminated: float = 0.0,
) -> dict:
    """
    Phase 5.3: Fiscal health check — trust solvency, purchasing power, levy sufficiency.

    Three pillars of fiscal health:
    1. Trust solvency: Can the Trust fund both stewardship and the sufficiency
       guarantee simultaneously? A solvent trust has positive surplus_deficit.
    2. Floor purchasing power trend: Is the floor PP index ≥ 1.0? Is it
       materially above baseline? (Principle 5 — it must never decline.)
    3. Levy sufficiency: Do levies cover at least LEVY_SUFFICIENCY_WARN fraction
       of the guarantee cost? Ensures fiscal burden sharing across the economy.

    Args:
        trust_balance: Current trust fund balance (TEH).
        labor_income: Annual TEH earned by workers.
        capital_stock_teh: Total capital stock value (TEH).
        capital_age_ratio: Mean asset age as fraction of design life.
        population: Total population.
        floor_teh: Sufficiency floor in TEH/year.
        epsilon: Automation level.
        suff_levy_rate: Sufficiency levy rate on labor income.
        dep_rate: Annual depreciation rate of trust.
        div_rate: Fraction of depreciation paid as dividend.
        baseline_basket_cost: Basket cost at ε=0.
        ecosystem_health: Ecosystem state ∈ [0, 1]. Used for ecological
            allocation sizing. Default: 0.70.
        deferred_ecological: Accumulated deferred ecological EOH. Default: 0.0.
        eco_eoh_override: Pre-computed ecological EOH from the pipeline.
            When provided, ecological_allocation() uses it directly rather than
            recomputing. Mirrors the infra_eoh_override pattern in fiscal_snapshot().
        capital_eoh_eliminated: EOH eliminated by capital stock, passed to
            stewardship_allocation() to match the pipeline's accounting.

    Returns:
        dict: {
          "trust_solvent":       bool,
          "trust_status":        str,   ("GREEN"/"RED")
          "trust_surplus_deficit": float,
          "pp_index":            float,
          "pp_status":           str,   ("GREEN"/"YELLOW"/"RED")
          "pp_gain_pct":         float,
          "levy_revenue":        float,
          "guarantee_cost":      float,
          "levy_to_guarantee_ratio": float,
          "levy_status":         str,
          "ecological_cost":     float,
          "ecological_status":   str,   ("GREEN"/"YELLOW"/"RED")
          "epsilon":             float,
        }

    Reference: Mission Statement §"Principle 2 — never depend on production for
    survival"; §"Principle 5 — The floor rises with automation; it never falls"
    """
    levies  = levy_collection(labor_income, {"sufficiency": suff_levy_rate})
    # new-13: translate capital_eoh_eliminated to infra_eoh_override, matching the
    # fiscal_snapshot() accounting pattern so stewardship sizing is in sync with
    # what total_eoh() has already eliminated.
    _infra_override = None
    if capital_eoh_eliminated > 0.0:
        from hours_eoh.core.eoh_generation import infrastructure_eoh as _infra_eoh
        _raw_infra = _infra_eoh(capital_stock_teh, capital_age_ratio, epsilon)
        _reduction  = max(0.0, 1.0 - capital_eoh_eliminated / max(_raw_infra, 1.0))
        _infra_override = _raw_infra * _reduction
    stew    = stewardship_allocation(capital_stock_teh, capital_age_ratio,
                                     epsilon, available_teh=trust_balance,
                                     infra_eoh_override=_infra_override)
    # new-3: ecological allocation is co-equal with stewardship — both draw
    # from the full Trust balance independently (neither is residual).
    eco     = ecological_allocation(ecosystem_health, epsilon,
                                    available_teh=trust_balance,
                                    deferred=deferred_ecological,
                                    eco_eoh_override=eco_eoh_override)
    guar    = sufficiency_guarantee(population, epsilon)
    trust   = trust_management(trust_balance, levies["total_levied"],
                                stew["teh_allocated"] + eco["teh_allocated"],
                                guar["total_cost_teh"],
                                dep_rate, div_rate, epsilon)
    pp      = floor_purchasing_power(floor_teh, epsilon, baseline_basket_cost)

    # Trust status
    trust_status = "GREEN" if trust["solvent"] else "RED"

    # PP status: must be ≥ 1.0 (Principle 5 hard requirement)
    # YELLOW if pp_index lags the continuous expected gain: threshold = 1 + slope×ε.
    # At ε=0.40 this equals PP_INDEX_WARN (1.05); removes the ε=0.40 blind spot.
    pp_index = pp["pp_index"]
    pp_warn_threshold = 1.0 + PP_INDEX_WARN_SLOPE * epsilon
    if pp_index < 1.0 - 1e-9:
        pp_status = "RED"     # Principle 5 violation — never allowed
    elif pp_index < pp_warn_threshold:
        pp_status = "YELLOW"  # lagging expected PP rise for this automation level
    else:
        pp_status = "GREEN"

    # Levy sufficiency: levy revenue vs. guarantee cost
    levy_revenue = levies["total_levied"]
    guarantee_cost = guar["total_cost_teh"]
    levy_ratio = levy_revenue / max(guarantee_cost, 1.0)
    if levy_ratio >= LEVY_SUFFICIENCY_WARN:
        levy_status = "GREEN"
    else:
        levy_status = "YELLOW"  # levy covers less than half of guarantee; trust must cover more

    # new-3: ecological status — healthy when allocated amount is covered by Trust
    eco_cost = eco["teh_allocated"]
    eco_status = "GREEN" if eco_cost <= trust_balance * 0.30 else (
                 "YELLOW" if eco_cost <= trust_balance * 0.60 else "RED")

    return {
        "trust_solvent":           trust["solvent"],
        "trust_status":            trust_status,
        "trust_surplus_deficit":   trust["surplus_deficit"],
        "pp_index":                pp_index,
        "pp_status":               pp_status,
        "pp_gain_pct":             pp["pp_gain_pct"],
        "levy_revenue":            levy_revenue,
        "guarantee_cost":          guarantee_cost,
        "levy_to_guarantee_ratio": levy_ratio,
        "levy_status":             levy_status,
        "ecological_cost":         eco_cost,
        "ecological_status":       eco_status,
        "epsilon":                 epsilon,
    }


# ---------------------------------------------------------------------------
# Full System Dashboard
# ---------------------------------------------------------------------------

def system_dashboard(
    epsilon: float,
    *,
    # Condition I — Ledger Identity
    teh_created: float,
    teh_destroyed: float,
    teh_observed: float,
    # Condition II — Multiplier Band
    segments: list[dict] | None = None,
    # Condition III — Zero Interest
    balance_start: float,
    earnings: float,
    expenditures: float,
    balance_end: float,
    # Condition IV — Distributed Competency
    certified_by_domain: dict[str, float],
    workforce_size: float,
    # EOH Health (5.2)
    total_eoh: float,
    fulfilled_eoh: float,
    deferred_eoh: float = 0.0,
    asset_type: str = "generic_infra",
    time_deferred: float = 0.0,
    registration_share: float | None = None,
    # Fiscal Health (5.3)
    trust_balance: float,
    labor_income: float,
    capital_stock_teh: float,
    capital_age_ratio: float,
    population: float,
    floor_teh: float,
    suff_levy_rate: float = SUFF_LEVY_RATE,
    dep_rate: float = DEP_RATE,
    div_rate: float = DIV_RATE,
    # Contestability (reconciliation §8) — computed by the caller
    chi: float | None = None,
    exit_financeable: bool | None = None,
) -> dict:
    """
    Full system health dashboard — all four conditions plus health indicators.

    Combines Condition monitors (Phase 1 conditions.py), EOH health indicators
    (Phase 5.2), and fiscal health (Phase 5.3) into a single structural
    integrity report. The overall status is the worst of all individual statuses.

    Contestability lives in research/ and core/ cannot import it (layer rules),
    so the caller computes the verdict and passes it in as a plain value.

    Two inputs, and which one you pass decides what is being asserted:

    - `exit_financeable` (PREFERRED, §8.9): the adopted three-channel invariant
      from research/recalibration.exit_financing()["exit_financeable"]. When
      supplied it GOVERNS the contestability status — False raises the RED flag,
      True is GREEN — and χ, if also supplied, is demoted to a YELLOW advisory.
    - `chi` (SUPERSEDED, §8 as originally written): χ = P/K_entry from
      research/contestability.contestability_margin(). Retained for callers that
      predate §8.9 and as a stricter stress: it asks whether ONE YEAR of income
      covers the whole founding stock, which is the RC4 flow/stock mismatch that
      §8.9 retired. When it is the only input supplied, the pre-§8.9 behavior is
      unchanged (χ < 1 → RED, χ < 1.2 → YELLOW).

    A failing χ alongside a financeable exit is the EXPECTED reading at shipped
    defaults, not a breach — which is why passing χ alone now understates the
    system's contestability.

    When both are None (default), contestability is not assessed.

    Args:
        epsilon: Automation level.
        teh_created: Cumulative TEH created through EOH fulfillment.
        teh_destroyed: Cumulative TEH destroyed (consumption + write-downs).
        teh_observed: TEH currently in circulation (from ledger).
        segments: Workforce segments for mean multiplier. Default: DEFAULT_SEGMENTS.
        balance_start: Account balance at period start (Condition III).
        earnings: Period earnings (Condition III).
        expenditures: Period expenditures (Condition III).
        balance_end: Account balance at period end (Condition III).
        certified_by_domain: Dict of certified worker counts per essential domain.
        workforce_size: Total active workforce.
        total_eoh: Total EOH demand this period.
        fulfilled_eoh: EOH actually fulfilled this period.
        deferred_eoh: Accumulated unfulfilled EOH (optional).
        asset_type: Asset type for compounding calculation.
        time_deferred: Years the backlog has been accumulating.
        registration_share: Override for registration coverage.
        trust_balance: Trust fund balance (TEH).
        labor_income: Annual labor income (TEH).
        capital_stock_teh: Total capital stock value.
        capital_age_ratio: Mean asset age fraction.
        population: Total population.
        floor_teh: Sufficiency floor TEH/year.
        suff_levy_rate: Levy rate on labor income.
        dep_rate: Trust annual depreciation rate.
        div_rate: Dividend fraction of depreciation.
        chi: SUPERSEDED contestability margin χ = P/K_entry, computed by the
            caller via research/contestability.contestability_margin().
            None = not supplied.
        exit_financeable: The adopted §8.9 invariant, from the caller's
            research/recalibration.exit_financing(). Governs the contestability
            status when supplied. None = not supplied.

    Returns:
        dict: {
          "condition_i":   dict,   (from condition_i_check)
          "condition_ii":  dict,   (from condition_ii_check)
          "condition_iii": dict,   (from balance_check)
          "condition_iv":  dict,   (from competency_check)
          "eoh_health":    dict,   (from eoh_health_indicators)
          "fiscal_health": dict,   (from fiscal_health_check)
          "contestability_chi":   float | None,  (echo of chi input)
          "contestability_status": str,  ("GREEN"/"YELLOW"/"RED"/"NOT_ASSESSED")
          "conditions_all_pass":  bool,
          "overall_status":       str,   ("GREEN"/"YELLOW"/"RED")
          "red_flags":            list[str],
          "yellow_flags":         list[str],
          "epsilon":              float,
        }

    Reference: Mission Statement §"Principle 8 — The code is the
    constitution's test bench. All four conditions must show green."
    """
    if segments is None:
        segments = DEFAULT_SEGMENTS

    # Condition I — Ledger Identity
    mean_mu = population_weighted_mean_multiplier(segments)
    c1 = condition_i_check(teh_created, teh_destroyed, teh_observed)
    c2 = condition_ii_check(mean_mu, M_BAND_LOW, M_BAND_HIGH)
    c3 = balance_check(balance_start, earnings, expenditures, balance_end)

    # Condition IV via competency_check
    reserve = competency_reserve(certified_by_domain, workforce_size)
    c4      = competency_check(reserve)

    # EOH health indicators
    eoh_h = eoh_health_indicators(
        total_eoh, fulfilled_eoh, epsilon,
        deferred_eoh, asset_type, time_deferred, registration_share,
    )

    # Fiscal health
    fis_h = fiscal_health_check(
        trust_balance, labor_income, capital_stock_teh, capital_age_ratio,
        population, floor_teh, epsilon, suff_levy_rate, dep_rate, div_rate,
    )

    # Overall assessment
    conditions_pass = (
        c1["passes"] and c2["in_band"] and c3["passes"] and c4["passes"]
    )

    red_flags: list[str] = []
    yellow_flags: list[str] = []

    if not c1["passes"]:
        red_flags.append(f"Condition I (Ledger Identity): {c1['status']}")
    if not c2["in_band"]:
        red_flags.append(f"Condition II (Multiplier Band): {c2['status']}")
    if not c3["passes"]:
        red_flags.append(f"Condition III (Zero Interest): {c3['status']}")
    if not c4["passes"]:
        red_flags.append(f"Condition IV (Competency Reserve): {c4['status']}")

    for indicator, key in (
        ("eoh_deferred", "deferred_ratio_status"),
        ("eoh_compounding", "compounding_status"),
        ("eoh_registration", "registration_status"),
        ("care_admission", "care_admission_status"),
    ):
        status = eoh_h[key]
        if status == "RED":
            red_flags.append(f"EOH health — {indicator}: RED")
        elif status == "YELLOW":
            yellow_flags.append(f"EOH health — {indicator}: YELLOW")

    for indicator, key in (
        ("trust_solvency", "trust_status"),
        ("floor_pp", "pp_status"),
        ("levy_sufficiency", "levy_status"),
    ):
        status = fis_h[key]
        if status == "RED":
            red_flags.append(f"Fiscal — {indicator}: RED")
        elif status == "YELLOW":
            yellow_flags.append(f"Fiscal — {indicator}: YELLOW")

    # Contestability (reconciliation §8, amended §8.9 2026-08-05).
    #
    # The ADOPTED invariant is three-channel exit financeability; χ = P/K_entry is
    # the retired flow/stock test kept as a stricter stress. So when the caller
    # supplies `exit_financeable`, it GOVERNS the status and χ is demoted to a
    # YELLOW advisory — a failing χ alongside a financeable exit is the expected
    # reading, not a breach. When the caller supplies only χ (the pre-§8.9 call
    # shape), behavior is unchanged.
    if exit_financeable is False:
        contestability_status = "RED"
        red_flags.append(
            "Contestability — exit not financeable through any channel (§8.9 invariant breached)"
        )
        if chi is not None and chi < CONTESTABILITY_CHI_CRIT:
            yellow_flags.append(
                f"Contestability — χ = {chi:.3f} < {CONTESTABILITY_CHI_CRIT} "
                f"(superseded stress, consistent with the breach)"
            )
    elif exit_financeable is True:
        contestability_status = "GREEN"
        if chi is not None and chi < CONTESTABILITY_CHI_CRIT:
            yellow_flags.append(
                f"Contestability — exit financeable, but the superseded χ = {chi:.3f} "
                f"< {CONTESTABILITY_CHI_CRIT}: exit is not self-financeable from one "
                f"year's income alone"
            )
    elif chi is None:
        contestability_status = "NOT_ASSESSED"
    elif chi < CONTESTABILITY_CHI_CRIT:
        contestability_status = "RED"
        red_flags.append(
            f"Contestability — χ = {chi:.3f} < {CONTESTABILITY_CHI_CRIT}: exit is nominal"
        )
    elif chi < CONTESTABILITY_CHI_WARN:
        contestability_status = "YELLOW"
        yellow_flags.append(
            f"Contestability — χ = {chi:.3f} < {CONTESTABILITY_CHI_WARN}: margin thinning"
        )
    else:
        contestability_status = "GREEN"

    if red_flags:
        overall_status = "RED"
    elif yellow_flags:
        overall_status = "YELLOW"
    else:
        overall_status = "GREEN"

    return {
        "condition_i":          c1,
        "condition_ii":         c2,
        "condition_iii":        c3,
        "condition_iv":         c4,
        "eoh_health":           eoh_h,
        "fiscal_health":        fis_h,
        "contestability_chi":   chi,
        "contestability_exit_financeable": exit_financeable,
        "contestability_status": contestability_status,
        "conditions_all_pass":  conditions_pass,
        "overall_status":       overall_status,
        "red_flags":            red_flags,
        "yellow_flags":         yellow_flags,
        "epsilon":              epsilon,
    }
