"""
EOH Generation Functions

Model the four entropy domains. These functions return the total EOH generated
by each domain — the labor demand that physical reality creates. EOH generation
is independent of who fulfills it (human or machine). The human share is
handled separately by human_eoh_share() in eoh_fulfillment.py.

**Physical state design**: EOH generation functions take physical state parameters
(capital_stock, ecosystem_health, monitoring_capability, knowledge_base_size,
age_distribution). They do NOT use ε as a proxy for unspecified physical state.
For cross-sectional analysis at a given ε, use trajectory.canonical_physical_state(ε)
to obtain the canonical physical state and pass it explicitly.

Each function retains an optional `epsilon` keyword for backward compatibility.
When provided, it fills in canonical-trajectory defaults for any physical state
not otherwise specified. New code should pass physical state directly.

Mission Statement: §"The four entropy domains" (personal, infrastructure,
ecological, knowledge); §"What an economy is" — civilization's organized
resistance to entropy; §"Guardrail I — Physical grounding" — EOH rates derived
from measurable physical indicators, not from policy or fiscal convenience.
"""

from __future__ import annotations
import math

from hours_eoh.data import (
    AGE_GROUPS, ESSENTIAL_DOMAINS,
    CANONICAL_CAPITAL_GROWTH_SLOPE,
    CANONICAL_MONITORING_CAPABILITY_BASE,
    CANONICAL_MONITORING_CAPABILITY_SLOPE,
    CANONICAL_KNOWLEDGE_COMPLEXITY_SLOPE,
    CANONICAL_KNOWLEDGE_COMPLEXITY_EXP,
)


# ---------------------------------------------------------------------------
# EOH generation calibration constants (physics, not trajectory)
# ---------------------------------------------------------------------------
_ECOLOGICAL_SPIKE_INTENSITY: float = 5.0   # nonlinear spike multiplier below ecological threshold
# Trajectory-scaling constants (CANONICAL_*) are in data.py and used only
# when epsilon is provided as a backward-compat canonical-trajectory lookup.


def _resolve_monitoring_capability(
    monitoring_capability: float | None,
    epsilon: float | None,
) -> float:
    """
    Resolve the effective monitoring capability from optional explicit and epsilon inputs.

    Priority: explicit value > epsilon-derived canonical > canonical base (ε=0 default).
    Shared by ecological_eoh() and ecological_eoh_breakdown() to keep the resolution
    logic in one place.
    """
    if monitoring_capability is not None:
        return max(0.0, min(1.0, monitoring_capability))
    if epsilon is not None:
        return CANONICAL_MONITORING_CAPABILITY_BASE + CANONICAL_MONITORING_CAPABILITY_SLOPE * epsilon
    return CANONICAL_MONITORING_CAPABILITY_BASE


# ---------------------------------------------------------------------------
# Personal EOH
# ---------------------------------------------------------------------------

def personal_eoh(
    population: float,
    age_distribution: dict[str, float] | None = None,
    epsilon: float | None = None,
    base_rate: float = 1500.0,
) -> float:
    """
    Total personal EOH generated by the population.

    Personal EOH is pure biology — the entropy obligations that human bodies
    generate simply by existing. Biology does not change with automation; what
    changes is the human vs. machine share of fulfillment (handled by
    human_eoh_share() in eoh_fulfillment.py).

    **Physical state input**: age_distribution is the explicit physical parameter.
    If None and epsilon is provided, the canonical age distribution for that ε
    is used (trajectory.canonical_age_distribution(ε)). If both are None, the
    AGE_GROUPS default fractions are used.

    Args:
        population: Total population count.
        age_distribution: Dict mapping group name → fraction of population.
                          Keys must match AGE_GROUPS. Defaults to AGE_GROUPS
                          fractions (or canonical arc if epsilon is provided).
        epsilon: Optional automation level [0.0, 0.99]. When provided and
                 age_distribution is None, fills in the canonical age distribution
                 for that ε. Does not otherwise affect the physics.
        base_rate: Personal EOH per working-age-equivalent person per year (hours).
                   Default: 1500 h/yr — food, shelter, healthcare, sanitation.

    Returns:
        Total personal EOH (hours/year) — the demand signal, not the supply.

    Reference: Mission Statement §"Personal EOH — the entropy of human bodies";
    §"Biology does not change with automation."
    """
    if age_distribution is None:
        if epsilon is not None:
            from hours_eoh.core.trajectory import canonical_age_distribution
            age_distribution = canonical_age_distribution(epsilon)
        else:
            age_distribution = {k: v["fraction"] for k, v in AGE_GROUPS.items()}

    weighted_pop = 0.0
    for group, fraction in age_distribution.items():
        weight = AGE_GROUPS[group]["eoh_weight"] if group in AGE_GROUPS else 1.0
        weighted_pop += population * fraction * weight

    return weighted_pop * base_rate


# ---------------------------------------------------------------------------
# Infrastructure EOH
# ---------------------------------------------------------------------------

def infrastructure_eoh(
    capital_stock: float,
    capital_age_ratio: float = 0.50,
    epsilon: float | None = None,
    base_maint_rate: float = 0.025,
    age_factor_max: float = 2.0,
) -> float:
    """
    Total infrastructure EOH generated by the built capital stock.

    Infrastructure maintenance burden scales with (a) the size of the capital
    stock and (b) how old/degraded the assets are. EOH generation is a property
    of what has been built, not of the automation level per se.

    **Physical state input**: capital_stock is the ACTUAL current stock in TEH
    (not an ε=0 baseline). The simulation tracks actual capital stock as it grows
    through investment; that value is passed directly here. The stewardship
    economy's core dynamic — growing capital stock generating growing entropy
    obligations — is expressed by passing the actual stock, which grows as
    simulate_period() invests each period.

    **Backward compatibility**: If epsilon is provided, capital_stock is treated
    as the ε=0 baseline and the canonical capital growth factor is applied:
    effective_capital = capital_stock × (1 + CANONICAL_CAPITAL_GROWTH_SLOPE × ε).
    This preserves existing test and cross-sectional analysis behaviour.
    New simulation code should track actual capital stock and omit epsilon.

    Args:
        capital_stock: Actual current capital stock in TEH. When epsilon is
                       provided (legacy), treated as ε=0 baseline and scaled.
        capital_age_ratio: Mean(current_age / design_life) across assets, ∈ [0, 1].
                           0 = all brand-new; 1 = all at end of design life.
        epsilon: Optional. When provided, applies canonical capital growth scaling
                 for backward compatibility. New code should omit this and pass
                 actual capital stock directly.
        base_maint_rate: EOH per TEH of capital at age_ratio=0 (fraction/year).
        age_factor_max: Maximum maintenance multiplier at capital_age_ratio=1.

    Returns:
        Total infrastructure EOH (hours/year).

    Reference: Mission Statement §"Infrastructure EOH — the entropy of built systems";
    §"The stewardship economy — growing capital stock generates growing entropy
    obligations, shifting the economy toward maintenance."
    """
    age_factor = 1.0 + (age_factor_max - 1.0) * capital_age_ratio
    if epsilon is not None:
        # Legacy: capital_stock is ε=0 baseline; apply canonical growth
        effective_capital = capital_stock * (1.0 + CANONICAL_CAPITAL_GROWTH_SLOPE * epsilon)
    else:
        effective_capital = capital_stock
    return effective_capital * base_maint_rate * age_factor


def infrastructure_statutory_floor(asset_census: list[dict]) -> float:
    """
    Task-normative infrastructure EOH floor from a physical condition census —
    currency-free.

    Governing equation:
        floor = Σ_bucket  count · hours_per_unit_year

    Each census bucket is a physical count of assets in a given condition and the
    task-normative labour-hours per unit per year to inspect/maintain them (e.g.
    (12 / inspection_interval_months) · crew_hours_per_visit). No money→hours
    conversion enters — this is the auditable, measured stream. Motivated by the
    NBI calibration (handoffs/Infrastructure): flipping any physical knob moves
    this floor; flipping an accounting convention does not, because there is none.

    units: hours/year. ε-behavior: none — maintenance burden is a property of what
    is built and its condition, not of the automation level (ε enters fulfilment,
    not this generation floor).

    Worked example: 8,019 good @ 8 h + 12,482 fair @ 20 h + 2,813 poor @ 48 h
        = 64,152 + 249,640 + 135,024 = 448,816 h/yr.

    Args:
        asset_census: list of buckets, each a dict with keys
            "count" (float ≥ 0) and "hours_per_unit_year" (float ≥ 0).

            OPTIONAL thermal keys are read by the census's other consumer and
            IGNORED here: "type" (a CAPITAL_THERMAL_PROFILES key), "teh_per_unit",
            "condition", "design_life_years". The same physical inventory yields
            both the labour floor (hours, this function) and the dissipation floor
            (watts, research/thermal_capital.infrastructure_thermal_floor) — the
            §12.2 dual-output property at census granularity. Specifying them
            together costs nothing; retrofitting means re-surveying.

    Returns:
        Total statutory-floor EOH (hours/year).

    Raises:
        ValueError: if any count or hours_per_unit_year is negative or a bucket
            is missing a required key.

    Reference: handoffs/Infrastructure §4.4 (statutory floor survives); Mission
    Statement Guardrail I (physical grounding).
    """
    total = 0.0
    for i, bucket in enumerate(asset_census):
        try:
            count = float(bucket["count"])
            hpu = float(bucket["hours_per_unit_year"])
        except (KeyError, TypeError) as exc:
            raise ValueError(
                f"census bucket {i} needs 'count' and 'hours_per_unit_year': {bucket!r}"
            ) from exc
        if count < 0.0 or hpu < 0.0:
            raise ValueError(f"census bucket {i} has negative count/hours: {bucket!r}")
        total += count * hpu
    return total


def infrastructure_eoh_breakdown(
    capital_stock: float | None = None,
    capital_age_ratio: float = 0.50,
    asset_census: list[dict] | None = None,
    discretionary_eoh: float = 0.0,
    deferred_stock: float = 0.0,
    monitoring_capability: float | None = None,
    epsilon: float | None = None,
    base_maint_rate: float = 0.025,
    age_factor_max: float = 2.0,
    assessment_id: str = "none",
) -> dict:
    """
    Infrastructure EOH split into a measured floor and a convention-laden remainder.

    The B+D design (author-selected 2026-07-31). infrastructure_eoh() returns a
    single float that conceals two halves of very different epistemic status. This
    companion separates them, mirroring ecological_eoh_breakdown():

        statutory_floor  — task-normative, currency-free, AUDITED when an
                           asset_census is supplied; the measured stream.
        discretionary    — maintenance ambition ABOVE the floor. Doctrine/
                           convention-dependent → a policy choice that belongs in
                           the fulfilment/fiscal layer, quarantined here as an input.
        visible_deferred — accrued-but-unfulfilled obligation made visible by
                           monitoring (deferred_stock · monitoring_factor).
        total = statutory_floor + discretionary + visible_deferred

    This is the same "floor = measurement, above the floor = discovery/politics"
    move as the price-as-floor reconciliation (§3) and the measured multiplier —
    infrastructure as the third domain under one epistemics.

    Two input paths:
      - asset_census (PRIMARY, physical): the floor is
        infrastructure_statutory_floor(asset_census); audited=True. Currency never
        enters, so ε's infrastructure denominator can honestly be this floor
        (handoffs/Infrastructure §5.4b) — the [0.04, 0.40] ε-indeterminacy of the
        monetized path collapses to a physical count.
      - capital_stock (FALLBACK, monetized): the floor is infrastructure_eoh(...);
        audited=False. With discretionary=0 and deferred=0 the total EQUALS
        infrastructure_eoh() with the same args — full backward compatibility.

    ε-behavior: the census floor is ε-invariant (physical). The scalar-fallback
    floor applies the legacy canonical growth when epsilon is given (unchanged).
    Degrades gracefully across ε ∈ [0, 0.99]; monitoring_factor is clamped.

    Args:
        capital_stock: monetized stock (TEH) for the fallback path. Required when
            asset_census is None.
        capital_age_ratio: mean age/design-life ∈ [0, 1] (fallback path only).
        asset_census: physical condition census (see infrastructure_statutory_floor).
            When provided, takes precedence over capital_stock for the floor.
        discretionary_eoh: policy ambition above the floor (hours/year); default 0.
        deferred_stock: accrued unfulfilled obligation (hours); default 0.
        monitoring_capability: fraction of deferred visible ∈ [0, 1]; resolved from
            epsilon when None (shared with the ecological path).
        epsilon: automation level; fallback-path canonical growth + monitoring default.
        base_maint_rate, age_factor_max: fallback-path rate model parameters.
        assessment_id: label naming the doctrine/source behind discretionary_eoh.

    Returns:
        dict: {
          "statutory_floor":  float,   (measured/auditable floor)
          "discretionary":    float,   (convention-dependent ambition)
          "visible_deferred": float,   (deferred_stock · monitoring_factor)
          "total":            float,   (= floor + discretionary + visible_deferred)
          "audited":          bool,    (True iff a physical census produced the floor)
          "monitoring_factor": float,
          "assessment_id":    str,
          "epsilon":          float | None,
        }

    Raises:
        ValueError: if neither asset_census nor capital_stock is provided.

    Reference: handoffs/Infrastructure §5.1–5.4; reconciliation §3 (floor semantics);
    Mission Statement Guardrail I.
    """
    if asset_census is not None:
        floor = infrastructure_statutory_floor(asset_census)
        audited = True
    elif capital_stock is not None:
        floor = infrastructure_eoh(
            capital_stock, capital_age_ratio, epsilon, base_maint_rate, age_factor_max
        )
        audited = False
    else:
        raise ValueError("infrastructure_eoh_breakdown needs asset_census or capital_stock")

    mon = _resolve_monitoring_capability(monitoring_capability, epsilon)
    visible_deferred = max(0.0, deferred_stock) * mon

    return {
        "statutory_floor":  floor,
        "discretionary":    discretionary_eoh,
        "visible_deferred": visible_deferred,
        "total":            floor + discretionary_eoh + visible_deferred,
        "audited":          audited,
        "monitoring_factor": mon,
        "assessment_id":    assessment_id,
        "epsilon":          epsilon,
    }


# ---------------------------------------------------------------------------
# Ecological EOH
# ---------------------------------------------------------------------------

def ecological_eoh(
    ecosystem_health: float,
    epsilon: float | None = None,
    base_rate: float = 500_000.0,
    threshold: float = 0.40,
    deferred: float = 0.0,
    monitoring_capability: float | None = None,
) -> float:
    """
    Total ecological EOH generated by natural systems civilization depends on.

    Three-component formula:

        baseline        = base_rate / ecosystem_health                      [h/yr]
        spike           = base_rate × 5 × ((threshold − health) / threshold)²
                          (only when ecosystem_health < threshold; else 0)  [h/yr]
        visible_deferred = deferred × monitoring_capability                 [h/yr]

        total = baseline + spike + visible_deferred

    Ecological systems do not degrade smoothly — long periods of slow
    accumulation are punctuated by sharp threshold failures (fishery collapse,
    soil depletion, aquifer loss, climate tipping points). The spike captures
    this: below health=0.40, EOH surges nonlinearly.

    As ε rises from 0 to 1, baseline EOH stays flat (ecosystem health degrades
    slightly on canonical arc, keeping baseline roughly constant), but
    visible_deferred grows with monitoring capability — better sensing makes
    historical neglect legible.

    Worked example (above threshold, ε=0.40, no deferred):
        health=0.82, monitoring=0.70 (canonical at ε=0.40)
        baseline = 500,000 / 0.82 = 610K h/yr
        spike    = 0 (health above threshold)
        total    = 610K h/yr

    Worked example (below threshold, ε=0.40):
        health=0.30, threshold=0.40, monitoring=0.70
        baseline = 500,000 / 0.30 = 1,667K h/yr
        spike    = 500,000 × 5 × ((0.40−0.30)/0.40)² = 156K h/yr
        total    = 1,823K h/yr  (+3× compared to healthy ecosystem)

    **Physical state input**: monitoring_capability is the explicit physical
    parameter, ∈ [0.0, 1.0]. When provided, takes precedence over the
    epsilon-derived canonical value (0.50 + 0.50ε).

    Args:
        ecosystem_health: Current ecosystem state, ∈ [0.0, 1.0].
                          1.0 = pristine; 0.0 = effectively collapsed.
        epsilon: Optional. When provided and monitoring_capability is None,
                 supplies the canonical monitoring capability for that ε.
        base_rate: Baseline ecological EOH at ecosystem_health=1.0 (hours/year).
        threshold: Below this health level, the nonlinear spike activates.
        deferred: Accumulated deferred EOH from historical neglect (hours).
        monitoring_capability: Fraction of deferred EOH visible to the ledger,
                               ∈ [0.0, 1.0]. When provided, takes precedence
                               over the epsilon-derived canonical value.

    Returns:
        Total ecological EOH (hours/year) including baseline, spike, and
        monitoring-visible deferred obligations.

    Reference: Mission Statement §"Ecological EOH — the entropy of natural systems";
    §"EOH and compounding" — threshold-based, not exponential; §"Guardrail I —
    EOH rates derived from measurable physical indicators."
    """
    return ecological_eoh_breakdown(
        ecosystem_health, epsilon, base_rate, threshold, deferred, monitoring_capability
    )["total"]


# ---------------------------------------------------------------------------
# Knowledge EOH
# ---------------------------------------------------------------------------

def knowledge_eoh(
    knowledge_base_size: float,
    skill_decay_rate: float = 0.10,
    epsilon: float | None = None,
    base_rate: float = 100_000.0,
    epsilon_exponent: float = 2.0,
    complexity_per_unit: float | None = None,
) -> float:
    """
    Total knowledge EOH generated by the information entropy of civilization.

    At high automation, almost all remaining human contribution is knowledge
    maintenance, transmission, and judgment. Skills atrophy. Institutional
    memory fades. Software rots. Standards drift. This domain becomes dominant
    as ε → 1.0 — and is the hardest to verify, requiring careful consideration
    of registration standards (Mission Statement: §"Admitting knowledge EOH
    to the collective ledger will require careful consideration").

    The formula is: base_rate × effective_kbs × complexity_per_unit × skill_decay_rate.
    Both effective_kbs and complexity_per_unit are O(1) — knowledge EOH is O(kbs),
    not O(kbs²). Automated systems are more complex (larger kbs AND harder per-unit
    maintenance), which is why knowledge EOH grows sharply with ε.

    **Physical state input**: knowledge_base_size is the ACTUAL current knowledge
    base size relative to the ε=0 reference (1.0 = reference). complexity_per_unit
    is the per-unit maintenance difficulty factor (1.0 = reference, grows with
    system complexity at high automation). Pass both from simulation state or from
    trajectory.canonical_physical_state(ε).

    **Backward compatibility**: If epsilon is provided, knowledge_base_size is treated
    as the ε=0 baseline (typically 1.0) and the canonical growth factor is applied:
    effective_kbs = kbs × (1 + CANONICAL_KNOWLEDGE_COMPLEXITY_SLOPE × ε).
    complexity_per_unit is derived from the canonical trajectory if not explicitly
    provided. Old callers passing knowledge_base_size=1.0 and epsilon=ε get the
    same result as before.

    Args:
        knowledge_base_size: Actual knowledge base size relative to ε=0 reference.
                             When epsilon is provided (legacy), treated as ε=0
                             baseline and scaled by canonical growth factor.
        skill_decay_rate: Fraction of knowledge base requiring renewal per year.
        epsilon: Optional automation level [0.0, 0.99]. When provided, fills in
                 canonical-trajectory defaults and scales knowledge_base_size as
                 the ε=0 baseline. New code should omit this.
        base_rate: Baseline knowledge EOH at ε=0 reference conditions (hours/year).
        epsilon_exponent: Per-unit complexity growth exponent (canonical trajectory).
        complexity_per_unit: Per-unit maintenance difficulty, ∈ [1.0, ∞). When
                             provided, takes precedence over epsilon-derived value.

    Returns:
        Total knowledge EOH (hours/year).

    Reference: Mission Statement §"Knowledge EOH — the entropy of information
    systems"; §"At ε=0.99, remaining human labor is almost entirely care,
    judgment, and knowledge maintenance."
    """
    if epsilon is not None:
        # Legacy: kbs is ε=0 baseline; apply canonical knowledge growth
        effective_kbs = knowledge_base_size * (1.0 + CANONICAL_KNOWLEDGE_COMPLEXITY_SLOPE * epsilon)
        cpu = (
            complexity_per_unit if complexity_per_unit is not None
            else 1.0 + (epsilon ** epsilon_exponent) * CANONICAL_KNOWLEDGE_COMPLEXITY_SLOPE
        )
    else:
        effective_kbs = knowledge_base_size
        # cpu=1.0 is the ε=0 reference floor — physical-state callers are expected
        # to pass a measured complexity_per_unit; this is the no-automation baseline.
        cpu = complexity_per_unit if complexity_per_unit is not None else 1.0

    return base_rate * effective_kbs * cpu * skill_decay_rate


# ---------------------------------------------------------------------------
# Total EOH Aggregate
# ---------------------------------------------------------------------------

def effective_capital_from_stock(capital_stock: float, epsilon: float) -> float:
    """
    ε-adjusted effective capital stock.

    **Deprecated**: Use ``trajectory.effective_capital_from_epsilon()`` instead.
    That function is the canonical reference and is imported by fiscal/stewardship
    code. This function is retained only for backward compatibility.

    Args:
        capital_stock: Baseline capital stock in TEH (at ε=0).
        epsilon: Automation level [0.0, 0.99].

    Returns:
        Effective capital stock in TEH at this automation level.
    """
    from hours_eoh.core.trajectory import effective_capital_from_epsilon
    return effective_capital_from_epsilon(capital_stock, epsilon)


def ecological_eoh_breakdown(
    ecosystem_health: float,
    epsilon: float | None = None,
    base_rate: float = 500_000.0,
    threshold: float = 0.40,
    deferred: float = 0.0,
    monitoring_capability: float | None = None,
) -> dict:
    """
    Full component breakdown of ecological EOH: baseline + spike + visible deferred.

    ecological_eoh() returns the total only. This companion function exposes the
    three constituent terms for transparency (Guardrail I) and monitoring dashboards.
    The values here sum to ecological_eoh() with the same arguments.

    **Physical state input**: monitoring_capability is the explicit physical
    parameter (same as ecological_eoh()). When provided, takes precedence over
    the epsilon-derived canonical value.

    Args:
        ecosystem_health: Current ecosystem state ∈ [0.0, 1.0].
        epsilon: Optional. When provided and monitoring_capability is None,
                 supplies the canonical monitoring capability for that ε.
        base_rate: Baseline ecological EOH at ecosystem_health=1.0 (hours/year).
        threshold: Below this health level, the nonlinear spike activates.
        deferred: Accumulated deferred EOH from historical neglect (hours).
        monitoring_capability: Fraction of deferred EOH visible to the ledger,
                               ∈ [0.0, 1.0]. When provided, takes precedence.

    Returns:
        dict: {
          "baseline":         float,   (routine stewardship at current health)
          "spike":            float,   (nonlinear threshold spike; 0 if above threshold)
          "visible_deferred": float,   (deferred obligation visible at this ε)
          "total":            float,   (= baseline + spike + visible_deferred)
          "monitoring_factor": float,  (fraction of deferred that is visible)
          "in_threshold_spike": bool,
          "ecosystem_health": float,
          "deferred":         float,
          "epsilon":          float | None,
        }

    Reference: Mission Statement §"Ecological EOH — threshold-based, not exponential."
    """
    health = max(ecosystem_health, 0.001)
    baseline = base_rate / health

    spike = 0.0
    if health < threshold:
        deficit = (threshold - health) / threshold
        spike = base_rate * _ECOLOGICAL_SPIKE_INTENSITY * (deficit ** 2)

    mon = _resolve_monitoring_capability(monitoring_capability, epsilon)
    visible_deferred = deferred * mon

    return {
        "baseline":          baseline,
        "spike":             spike,
        "visible_deferred":  visible_deferred,
        "total":             baseline + spike + visible_deferred,
        "monitoring_factor": mon,
        "in_threshold_spike": ecosystem_health < threshold,
        "ecosystem_health":  ecosystem_health,
        "deferred":          deferred,
        "epsilon":           epsilon,
    }


def total_eoh(
    epsilon: float | None = None,
    population: float = 1_000_000.0,
    age_distribution: dict[str, float] | None = None,
    capital_stock: float = 2_000_000_000.0,
    capital_age_ratio: float = 0.50,
    ecosystem_health: float = 0.70,
    deferred_ecological: float = 0.0,
    knowledge_complexity: float = 1.0,
    skill_decay_rate: float = 0.10,
    # Per-domain base rates — allow override for calibration sweeps
    personal_base: float = 1500.0,
    infra_maint_rate: float = 0.025,
    ecological_base: float = 500_000.0,
    ecological_threshold: float = 0.40,
    knowledge_base: float = 100_000.0,
    knowledge_exponent: float = 2.0,
    capital_eoh_eliminated: float = 0.0,
    capital_personal_eoh_fulfilled: float = 0.0,
    infrastructure_compounding_eoh: float = 0.0,
    competency_gap_factor: float = 0.0,
    # Physical state parameters (new API — override canonical defaults when provided)
    monitoring_capability: float | None = None,
    knowledge_complexity_per_unit: float | None = None,
) -> dict[str, float]:
    """
    Aggregate EOH across all four domains.

    Returns a breakdown by domain plus the total, making the demand signal
    transparent and auditable (Guardrail I: physical grounding). This is the
    total entropy obligation of the civilization — what physics demands,
    independent of who (human or machine) fulfills it.

    **Physical state design**: When epsilon is None, each domain function uses
    only the explicit physical parameters passed here. When epsilon is provided,
    domain functions use canonical-trajectory defaults for any physical state
    not explicitly overridden. monitoring_capability and knowledge_complexity_per_unit
    always take precedence over the epsilon-derived canonical values when provided.

    Args:
        epsilon: Optional automation level [0.0, 0.99]. When provided, fills in
                 canonical-trajectory defaults for domain functions (backward compat).
                 New simulation code passes physical state directly and omits this.
        population: Total population.
        age_distribution: Optional dict mapping age group → fraction.
        capital_stock: Actual current capital stock in TEH. When epsilon is
                       provided (legacy), treated as ε=0 baseline and scaled.
        capital_age_ratio: Mean asset age relative to design life, ∈ [0, 1].
        ecosystem_health: Ecosystem state, ∈ [0, 1].
        deferred_ecological: Accumulated deferred ecological EOH (hours).
        knowledge_complexity: Knowledge base size relative to ε=0 reference.
                              When epsilon is provided, treated as ε=0 baseline
                              and scaled by canonical growth factor.
        skill_decay_rate: Annual fraction of skills requiring renewal.
        (+ per-domain base rates for calibration)
        capital_eoh_eliminated: Aggregate system EOH eliminated by the capital
            stock (sum of annual_eoh_eliminated across all assets). Applied
            proportionally to infrastructure/ecological/knowledge only — NOT
            personal EOH. Personal entropy (biological needs) is unaffected by
            capital stock size; only the human-labor burden decreases via (1-ε).
        capital_personal_eoh_fulfilled: Aggregate personal EOH fulfilled by the
            capital stock per year (sum of annual_personal_eoh_fulfilled across
            all assets). Passed through to the return dict so fiscal.py can
            compute per-capita fulfillment and reduce the guarantee's EOH
            reimbursement accordingly. Does NOT alter total personal EOH demand
            — the biological obligation still exists, but capital handles it.
        infrastructure_compounding_eoh: Deferred-maintenance compounding spike
            (pre-computed via eoh_compounding()) added to baseline infrastructure
            EOH. Converts deferred maintenance from an informational health warning
            into actual demand in the EOH ledger. Applied before capital_eoh_eliminated
            reduction so eliminated obligations are still removed from the compounded
            total.
        competency_gap_factor: Additional fractional amplification of knowledge EOH
            from competency gaps. When certified worker counts fall below the Condition
            IV threshold in essential domains, skill decay accelerates and recovery
            training increases knowledge EOH demand. Compute via
            competency_to_knowledge_eoh_delta() in workforce.py. Default 0.0 (no gap).
        monitoring_capability: Fraction of deferred ecological EOH visible to the
            ledger, ∈ [0.0, 1.0]. When provided, takes precedence over the
            epsilon-derived canonical value.
        knowledge_complexity_per_unit: Per-unit maintenance difficulty for knowledge
            EOH, ∈ [1.0, ∞). When provided, takes precedence over the epsilon-derived
            canonical value.

    Governing equation (additive across four physical domains):

        EOH_total = EOH_personal + EOH_infrastructure + EOH_ecological + EOH_knowledge

    Key non-obvious behavior: total EOH *rises* with ε on the canonical arc.
    Personal EOH is roughly flat (biological needs are constant), but infrastructure
    grows with capital stock, ecological EOH is held roughly flat at healthy values,
    and knowledge EOH grows steeply as ε² × knowledge_base_size. The automation
    paradox: more machines → more complex civilization → more entropy to maintain.

    Worked example at ε=0.40 (canonical defaults, population=1M):
        Personal:        2,217M h/yr  (1M people × ~2,217 h/yr avg weighted EOH)
        Infrastructure:    135M h/yr  (3.6B TEH capital × 0.025/yr × 1.5 age factor)
        Ecological:        714K h/yr  (healthy ecosystem, no deferred, 70% monitoring)
        Knowledge:         112K h/yr  (knowledge_base=4.6 × 0.10 decay × 100K base × 2.44/unit)
        Total:           2,353M h/yr

    Compare at ε=0.0 (subsistence): total = 2,288M h/yr
    Compare at ε=0.90 (high automation): total = 2,432M h/yr

    Returns:
        dict with keys: personal, infrastructure, ecological, knowledge, total,
        capital_eoh_eliminated, capital_personal_eoh_fulfilled,
        infrastructure_compounding_eoh, competency_gap_factor.
        All values in hours/year.

    Reference: Mission Statement §"Entropy Obligation Hours — Accounting Framework"
    """
    p = personal_eoh(population, age_distribution, epsilon, personal_base)
    i = infrastructure_eoh(capital_stock, capital_age_ratio, epsilon,
                           infra_maint_rate, 2.0) + infrastructure_compounding_eoh
    e = ecological_eoh(ecosystem_health, epsilon, ecological_base,
                       ecological_threshold, deferred_ecological, monitoring_capability)
    k = knowledge_eoh(knowledge_complexity, skill_decay_rate, epsilon,
                      knowledge_base, knowledge_exponent, knowledge_complexity_per_unit)

    # Competency gap feedback: undercertified domains accelerate skill decay,
    # increasing knowledge EOH demand. Applied before elimination so the extra
    # demand can still be offset by capital investments.
    if competency_gap_factor > 0.0:
        k *= (1.0 + competency_gap_factor)

    # Apply capital-stock EOH elimination to non-personal domains only.
    # Proportional reduction preserves relative domain shares; personal EOH is
    # unchanged to prevent the deflationary feedback loop where capital growth
    # reduces biological obligations and dampens TEH creation.
    if capital_eoh_eliminated > 0.0:
        non_personal = i + e + k
        if non_personal > 0.0:
            reduction_factor = 1.0 - capital_eoh_eliminated / non_personal
            i = max(0.0, i * reduction_factor)
            e = max(0.0, e * reduction_factor)
            k = max(0.0, k * reduction_factor)

    return {
        "personal":               p,
        "infrastructure":         i,
        "ecological":             e,
        "knowledge":              k,
        "total":                  p + i + e + k,
        "capital_eoh_eliminated":         capital_eoh_eliminated,
        "capital_personal_eoh_fulfilled":  capital_personal_eoh_fulfilled,
        "infrastructure_compounding_eoh":  infrastructure_compounding_eoh,
        "competency_gap_factor":           competency_gap_factor,
    }


# ---------------------------------------------------------------------------
# Domain labor requirements
# ---------------------------------------------------------------------------

def domain_labor_requirements(
    eoh_by_domain: dict,
    epsilon: float,
    hours_per_worker: float = 2000.0,
) -> dict:
    """
    Workers required in each EOH domain given current automation level.

    Translates the domain EOH breakdown (from total_eoh()) into headcount
    requirements by dividing the human-labor share by annual hours per worker.
    This makes the demand signal concrete for workforce planning: how many
    healthcare workers, infrastructure stewards, ecological monitors, etc.
    are needed to fulfill the human portion of each domain's EOH?

    The human fraction = (1 − ε) applies uniformly — automation handles
    (ε × domain_eoh) and the remaining (1−ε) requires human workers.

    Args:
        eoh_by_domain: Dict with keys "personal", "infrastructure",
                       "ecological", "knowledge" — typically from
                       total_eoh()[domain] or eoh_to_teh_pipeline()["eoh_by_domain"].
        epsilon: Automation level [0.0, 0.99]. Applied to all domains.
        hours_per_worker: Annual productive hours per worker. Default 2000
                          (H_REF from data.py — one full working year).

    Returns:
        dict: {
          "epsilon":        float,
          "human_fraction": float,      (= 1 − ε)
          "hours_per_worker": float,
          "domains": {
            <domain>: {
              "total_eoh":      float,  (gross physical obligation)
              "human_eoh":      float,  (portion requiring human labor)
              "workers_needed": float,  (human_eoh / hours_per_worker)
            },
            ...
          },
          "total_workers_needed": float,   (sum across all domains)
        }

    Reference: Mission Statement §"The workforce must be sized to its EOH
    obligation, not the other way around — scarcity of workers in any domain
    is a structural risk, not a labor-market outcome."
    """
    human_fraction = max(0.0, 1.0 - epsilon)
    h = max(hours_per_worker, 1.0)

    domains: dict = {}
    for name, total in eoh_by_domain.items():
        human = total * human_fraction
        domains[name] = {
            "total_eoh":      total,
            "human_eoh":      human,
            "workers_needed": human / h,
        }

    total_workers = sum(d["workers_needed"] for d in domains.values())

    return {
        "epsilon":              epsilon,
        "human_fraction":       human_fraction,
        "hours_per_worker":     hours_per_worker,
        "domains":              domains,
        "total_workers_needed": total_workers,
    }


# ---------------------------------------------------------------------------
# EOH to essential workforce domains
# ---------------------------------------------------------------------------

# Default weight matrix: rows = essential workforce domains, cols = EOH domains.
# Each column sums to 1.0 — every unit of aggregate EOH is attributed to
# exactly one essential domain. Agriculture leads on ecological EOH (farming
# is the primary ecosystem steward); healthcare on personal EOH (biological
# care); construction/energy/water/manufacturing/logistics divide infrastructure;
# knowledge EOH is distributed across all seven domains.
_EOH_TO_ESSENTIAL_WEIGHTS: dict[str, dict[str, float]] = {
    #                        personal  infrastructure  ecological  knowledge
    "agriculture":    {"personal": 0.00, "infrastructure": 0.05, "ecological": 0.50, "knowledge": 0.10},
    "construction":   {"personal": 0.00, "infrastructure": 0.25, "ecological": 0.00, "knowledge": 0.10},
    "energy":         {"personal": 0.00, "infrastructure": 0.20, "ecological": 0.10, "knowledge": 0.10},
    "water":          {"personal": 0.00, "infrastructure": 0.15, "ecological": 0.30, "knowledge": 0.10},
    "healthcare":     {"personal": 0.80, "infrastructure": 0.05, "ecological": 0.00, "knowledge": 0.30},
    "manufacturing":  {"personal": 0.00, "infrastructure": 0.20, "ecological": 0.05, "knowledge": 0.15},
    "logistics":      {"personal": 0.20, "infrastructure": 0.10, "ecological": 0.05, "knowledge": 0.15},
}
assert set(_EOH_TO_ESSENTIAL_WEIGHTS) == set(ESSENTIAL_DOMAINS), (
    "Weight matrix keys must match ESSENTIAL_DOMAINS — update _EOH_TO_ESSENTIAL_WEIGHTS "
    f"to cover: {set(ESSENTIAL_DOMAINS) - set(_EOH_TO_ESSENTIAL_WEIGHTS)}"
)


def eoh_to_essential_domains(
    eoh_by_domain: dict,
    weights: dict[str, dict[str, float]] | None = None,
) -> dict:
    """
    Distribute aggregate EOH across the seven essential workforce domains.

    The four EOH domains (personal, infrastructure, ecological, knowledge) are
    physical-obligation categories. The seven essential workforce domains
    (agriculture, construction, energy, water, healthcare, manufacturing,
    logistics) are certification categories for Condition IV. This function
    bridges them so that domain_eoh_coverage() can be called from aggregate
    simulation data.

    Each EOH domain is distributed proportionally across the seven essential
    domains using a weight matrix. The default weights are calibrated so each
    EOH domain column sums to 1.0 (every unit is fully attributed). Callers
    can override with a custom weight matrix for sector-specific models.

    Args:
        eoh_by_domain: Dict with any subset of "personal", "infrastructure",
                       "ecological", "knowledge" — from total_eoh() or
                       eoh_to_teh_pipeline()["eoh_by_domain"].
        weights: Optional weight matrix overriding _EOH_TO_ESSENTIAL_WEIGHTS.
                 Format: {essential_domain: {eoh_domain: fraction}}.
                 Default None → use _EOH_TO_ESSENTIAL_WEIGHTS.

    Returns:
        dict: {essential_domain: eoh_hours} for the seven essential domains.
              Values are in the same units as the input eoh_by_domain values.

    Reference: Mission Statement §"Condition IV — Distributed Competency" —
    certified capacity must cover EOH demand domain by domain, not just in aggregate.
    """
    w = weights if weights is not None else _EOH_TO_ESSENTIAL_WEIGHTS
    return {
        ess_domain: sum(
            eoh_by_domain.get(eoh_dom, 0.0) * frac
            for eoh_dom, frac in eoh_weights.items()
        )
        for ess_domain, eoh_weights in w.items()
    }


# ---------------------------------------------------------------------------
# Epsilon-delta sensitivity
# ---------------------------------------------------------------------------

def epsilon_delta_sensitivity(
    base_epsilon: float,
    delta_epsilon: float,
    population: float = 1_000_000.0,
    capital_stock: float = 2_000_000_000.0,
    capital_age_ratio: float = 0.50,
    ecosystem_health: float = 0.70,
    knowledge_complexity: float = 1.0,
    mean_multiplier: float = 2.10,
) -> dict:
    """
    How do key EOH/TEH metrics change for a given Δε automation advance?

    Answers the question: "if automation advances by Δε, what moves and by
    how much?" Returns base values, new values, absolute deltas, and
    percentage changes for the metrics most sensitive to automation progression.
    Useful for stress-test interpretation and tactical epsilon-progression
    planning.

    Metrics tracked:
    - total_eoh: gross physical entropy obligation
    - human_eoh: human-labor share (shrinks with ε)
    - teh_created: TEH generated this period
    - registration_share: composite registration fraction (rises with ε)
    - knowledge_eoh: knowledge domain (grows sharply at high ε)
    - workers_needed: total headcount implied by domain labor requirements

    Args:
        base_epsilon: Starting automation level [0.0, 0.99].
        delta_epsilon: Automation advancement. Can be negative for retreat.
                       Clamped so new_epsilon ∈ [0.0, 0.99].
        population: Population size (held fixed — this is a sensitivity, not simulation).
        capital_stock: Capital stock TEH.
        capital_age_ratio: Asset age.
        ecosystem_health: Ecosystem state.
        knowledge_complexity: Knowledge base size.
        mean_multiplier: TEH creation multiplier.

    Returns:
        dict: {
          "base_epsilon":  float,
          "new_epsilon":   float,
          "delta_epsilon": float,   (actual applied delta; may differ if clamped)
          "metrics": {
            <name>: {
              "base":     float,
              "new":      float,
              "delta":    float,    (new − base)
              "pct_change": float,  (delta / base × 100; None if base == 0)
            },
            ...
          },
        }

    Reference: Mission Statement §"Stress tests — identify failure boundaries";
    §"The system must remain coherent across the full automation arc."
    """
    from hours_eoh.core.eoh_fulfillment import eoh_to_teh_pipeline

    new_eps = max(0.0, min(0.99, base_epsilon + delta_epsilon))
    actual_delta = new_eps - base_epsilon

    def _snapshot(eps: float) -> dict:
        pipe = eoh_to_teh_pipeline(
            epsilon=eps,
            population=population,
            capital_stock=capital_stock,
            capital_age_ratio=capital_age_ratio,
            ecosystem_health=ecosystem_health,
            knowledge_complexity=knowledge_complexity,
            mean_multiplier=mean_multiplier,
        )
        req = domain_labor_requirements(pipe["eoh_by_domain"], eps)
        return {
            "total_eoh":        pipe["total_eoh"],
            "human_eoh":        pipe["human_eoh"],
            "teh_created":      pipe["teh_created"],
            "registration_share": pipe["registration_share"],
            "knowledge_eoh":    pipe["eoh_by_domain"].get("knowledge", 0.0),
            "workers_needed":   req["total_workers_needed"],
        }

    base = _snapshot(base_epsilon)
    new  = _snapshot(new_eps)

    def _pct(b: float, delta: float) -> float | None:
        return (delta / b * 100.0) if b != 0.0 else None

    metrics: dict = {}
    for name in base:
        b = base[name]
        n = new[name]
        d = n - b
        metrics[name] = {"base": b, "new": n, "delta": d, "pct_change": _pct(b, d)}

    return {
        "base_epsilon":  base_epsilon,
        "new_epsilon":   new_eps,
        "delta_epsilon": actual_delta,
        "metrics":       metrics,
    }
