"""
EOH Compounding, Regenerative Labor, Infrastructure Investment Logic

EOH compounding models how unfulfilled obligations generate additional EOH
over time. It is explicitly NOT interest, it measures physical reality, not
a social convention. The pattern is threshold-based and discontinuous, not
smooth and exponential. Long periods of slow accumulation are punctuated by
sharp threshold failures.

Regenerative labor differs from maintenance labor: maintenance fulfills current
EOH (and creates TEH); regenerative labor fulfills current EOH AND reduces future
EOH generation rates (composting, preventive maintenance, ecosystem restoration,
education/training).

Infrastructure investment logic answers: does building this asset eliminate more
personal EOH than its own maintenance will cost? The production economy's core
criterion — build what reduces aggregate EOH, not what maximizes return.

Mission Statement: §"EOH and compounding", §"Regenerative offset",
§"The production economy", EOH reduction through capital creation,
§"Infrastructure EOH — the economic logic of infrastructure investment"
"""

from __future__ import annotations
import math

from hours_eoh.data import (
    ASSET_TYPES,
    HUMAN_CAPITAL_NATURAL_DECAY,
    MONITORING_SPIKE_SOFTENING_MAX,
    PRE_THRESHOLD_COMPOUND_RATE,
    REGEN_AUTOMATION_LEVERAGE_MAX,
)
from hours_eoh.core.capital import asset_condition, writedown_trigger


# ---------------------------------------------------------------------------
# Compounding and regenerative calibration constants
# ---------------------------------------------------------------------------
# All three migrated to data.py 2026-08-28 as MONITORING_SPIKE_SOFTENING_MAX,
# PRE_THRESHOLD_COMPOUND_RATE and REGEN_AUTOMATION_LEVERAGE_MAX. All were
# shadow constants and none was pinned by any test.


# ---------------------------------------------------------------------------
# Deferred EOH (the maintenance deficit)
# ---------------------------------------------------------------------------

def deferred_eoh(
    accumulated_eoh: float,
    fulfilled_eoh: float,
) -> float:
    """
    The maintenance deficit: accumulated EOH obligation minus what was fulfilled.

    This is the structural gap that EOH compounding acts on. Deferred EOH
    is not a monetary debt — no one earns TEH from it existing. It persists
    until labor is directed toward it or the underlying capital fails.

    Args:
        accumulated_eoh: Total EOH generated by this asset to date (hours).
        fulfilled_eoh: Total EOH fulfilled toward this asset to date (hours).

    Returns:
        Deferred EOH (hours). Non-negative. Zero means fully maintained.

    Reference: Mission Statement §"The dual ledger" — "The gap between
    accumulated EOH and fulfilled EOH constitutes deferred maintenance —
    a deficit that is visible, quantifiable, and structurally distinct
    from monetary debt."
    """
    return max(0.0, accumulated_eoh - fulfilled_eoh)


# ---------------------------------------------------------------------------
# EOH Compounding (threshold-based, NOT exponential)
# ---------------------------------------------------------------------------

# Spike factors by asset type: how severe is the threshold failure event?
# Mission Statement: "stone bridge: slow; software: fast; ecosystem: slow then spike"
_SPIKE_FACTORS = {
    "stone_bridge":  1.5,   # structural failure is significant but moderate
    "software":      3.0,   # fast decay, failure is severe and rapid
    "ecosystem":     2.0,   # slow then spike (threshold ecology collapse)
    "building":      1.8,
    "power_grid":    2.2,   # critical systems fail dramatically at threshold
    "generic_infra": 1.9,
}


def eoh_compounding(
    deferred: float,
    asset_type: str,
    time_deferred: float,
    epsilon: float = 0.40,
) -> float:
    """
    Additional EOH generated by unfulfilled obligations over time.

    CRITICAL: This function returns additional EOH obligation — it does NOT
    create TEH. Only labor that fulfills EOH creates TEH. EOH compounding
    generates obligation without labor; TEH is created only when someone
    actually does the work. This is the key distinction from interest.

    The behavior is intentionally threshold-based and discontinuous:

    Pre-threshold (t < T):
      Slow, sub-linear growth. The system is degrading but still functional.
      Compounding is minor — routine neglect has moderate consequences.

    At threshold (t = T):
      Discontinuous spike. Structural failure event. The maintenance deficit
      suddenly demands vastly more labor to address (or rebuild from scratch).
      This is the "long periods of accumulation punctuated by sharp failure"
      described in the Mission Statement.

    Post-threshold (t > T):
      Rapid, power-law escalation. The system is in collapse; each additional
      period of neglect costs disproportionately more to address.

    Different asset types have different threshold ages and escalation profiles:
    - stone_bridge: threshold at 80 years, moderate escalation
    - software: threshold at 5 years, severe rapid escalation
    - ecosystem: threshold at 200 years, but spikes hard when breached

    Args:
        deferred: Accumulated deferred EOH (hours) — the maintenance deficit.
        asset_type: Key into ASSET_TYPES / _SPIKE_FACTORS. Use "generic_infra"
                    for unknown asset types.
        time_deferred: Time (years) since maintenance deficit began accumulating.
        epsilon: Automation level. At higher ε, automated monitoring may
                 catch some deterioration earlier, slightly softening the spike.

    Returns:
        Additional EOH generated by the compounding deficit (hours).
        Add to the asset's deferred_eoh to get total obligation.

    Raises:
        KeyError: If asset_type is not in ASSET_TYPES.

    Reference: Mission Statement §"EOH and compounding" — "Long periods of slow
    accumulation are punctuated by sharp threshold failures — a pattern that bears
    no resemblance to compound interest curves." §"Condition III — Zero Interest":
    EOH compounding ≠ monetary interest; no TEH created without labor.
    """
    if deferred <= 0 or time_deferred <= 0:
        return 0.0

    if asset_type not in ASSET_TYPES:
        raise KeyError(
            f"Unknown asset_type: {asset_type!r}. "
            f"Valid types: {list(ASSET_TYPES.keys())}"
        )

    profile    = ASSET_TYPES[asset_type]
    T          = float(profile["threshold_age"])
    exp        = float(profile["compound_exp"])
    spike      = _SPIKE_FACTORS.get(asset_type, 2.0)

    # Monitoring at higher ε softens the spike (better predictive maintenance)
    monitoring_softener = 1.0 - MONITORING_SPIKE_SOFTENING_MAX * epsilon

    t = float(time_deferred)

    if t < T:
        # Pre-threshold: concave (sub-linear) growth — slow accumulation
        # Formula: deferred × 0.10 × (t/T)^(1/exp)
        # At t→0: approaches 0. At t→T⁻: approaches 0.10 × deferred.
        # (1/exp) > 1 for exp<1, <1 for exp>1 — higher exp → more concave pre-threshold
        t_frac = t / T
        return deferred * PRE_THRESHOLD_COMPOUND_RATE * (t_frac ** (1.0 / exp))

    else:
        # At/beyond threshold: DISCONTINUOUS JUMP + power-law escalation
        # The discontinuity is the "sharp threshold failure" — the system passes
        # a tipping point beyond which its EOH obligation balloons.

        # Pre-threshold baseline (continuous part, just below T)
        pre = deferred * PRE_THRESHOLD_COMPOUND_RATE

        # Discontinuous spike at threshold: spike_factor × deferred
        # Plus power-law escalation with years beyond threshold
        post_years = t - T  # 0 at threshold, positive beyond
        escalation = spike * (1.0 + post_years) ** (exp - 1.0)
        spike_term = deferred * escalation * monitoring_softener

        return pre + spike_term


def compounding_profile(
    asset_type: str,
    deferred: float,
    max_years: float | None = None,
    epsilon: float = 0.40,
    n_points: int = 50,
) -> list[dict]:
    """
    Compute the compounding profile of an asset over time.

    Returns a time series showing additional EOH generated at each time point,
    making the threshold discontinuity visible and auditable.

    Args:
        asset_type: Key into ASSET_TYPES.
        deferred: Maintenance deficit (hours) to compound on.
        max_years: Duration to model. Defaults to 2 × threshold_age.
        epsilon: Automation level.
        n_points: Number of time points.

    Returns:
        List of dicts: [{"year": float, "additional_eoh": float,
                         "is_post_threshold": bool}, ...]

    Reference: Mission Statement §"EOH and compounding" — behavior should be
    transparent and physically auditable (Guardrail I).
    """
    T = float(ASSET_TYPES[asset_type]["threshold_age"])
    end = max_years if max_years is not None else 2.0 * T
    step = end / n_points

    result = []
    for i in range(n_points + 1):
        t = i * step
        result.append({
            "year":             t,
            "additional_eoh":   eoh_compounding(deferred, asset_type, t, epsilon),
            "is_post_threshold": t >= T,
        })
    return result


# ---------------------------------------------------------------------------
# Regenerative Labor
# ---------------------------------------------------------------------------

# Profiles for regenerative labor types.
# Each type specifies which EOH domain it reduces and the impact rate.
# "reduction_rate": EOH/year reduction per year worked (annualized).
# "amortization_years": how many future years the benefit persists.
REGENERATIVE_PROFILES: dict[str, dict] = {
    "composting": {
        "domain":              "ecological",
        "description":         "Enriches soil; reduces future agricultural EOH",
        # 1 hour of composting labor saves this many EOH/year going forward
        "eoh_saved_per_hour":  0.80,
        "amortization_years":  10,
    },
    "preventive_maintenance": {
        "domain":              "infrastructure",
        "description":         "Prevents threshold failures; reduces compounding EOH",
        "eoh_saved_per_hour":  2.50,   # high leverage: prevents spike events
        "amortization_years":  5,
    },
    "education_training": {
        "domain":              "knowledge",
        "description":         "Reduces skill decay rates; lowers future knowledge EOH",
        "eoh_saved_per_hour":  1.20,
        "amortization_years":  15,
    },
    "ecosystem_restoration": {
        "domain":              "ecological",
        "description":         "Raises ecosystem health; reduces baseline and spike EOH",
        "eoh_saved_per_hour":  1.50,
        "amortization_years":  20,
    },
    "infrastructure_upgrade": {
        "domain":              "infrastructure",
        "description":         "Extends design life; reduces annual maintenance burden",
        "eoh_saved_per_hour":  1.80,
        "amortization_years":  10,
    },
    "water_system_maintenance": {
        "domain":              "personal",
        "description":         "Maintains water supply; reduces personal EOH for population",
        "eoh_saved_per_hour":  3.00,   # high leverage: serves many people
        "amortization_years":  8,
    },
}


def regenerative_offset(
    labor_type: str,
    regenerative_hours: float,
    epsilon: float = 0.40,
) -> dict:
    """
    Calculate the future EOH reduction from a regenerative labor investment.

    Maintenance labor fulfills current EOH (creating TEH). Regenerative labor
    does the same — it fulfills current EOH and creates TEH at the worker's
    multiplier rate — but additionally reduces future EOH generation rates.

    This distinction carries significant implications for stewardship planning:
    a collective that invests in regenerative labor today can reduce its total
    entropy obligation over the medium term, even before automation rises.

    Note: TEH creation from regenerative labor is handled by the standard
    teh_created() pipeline. This function returns only the *additional*
    future benefit that distinguishes regenerative from maintenance labor.

    Args:
        labor_type: Key into REGENERATIVE_PROFILES (e.g., "composting",
                    "preventive_maintenance", "education_training").
        regenerative_hours: Hours of regenerative labor performed.
        epsilon: Automation level. At higher ε, some regenerative benefits
                 are amplified (automated monitoring extends impact).

    Returns:
        dict: {
          "labor_type": str,
          "domain": str,
          "hours_worked": float,
          "current_eoh_fulfilled": float,     (= hours, standard TEH creation)
          "future_eoh_reduction_per_year": float,  (annual EOH saved going forward)
          "amortization_years": int,
          "lifetime_eoh_savings": float,      (total EOH saved over amortization)
          "epsilon_leverage": float,          (automation amplification factor)
        }

    Raises:
        KeyError: If labor_type is not in REGENERATIVE_PROFILES.

    Reference: Mission Statement §"Regenerative offset" — "Some labor reduces
    future EOH rather than fulfilling current EOH. Composting enriches soil,
    reducing future agricultural labor needs. Preventive maintenance extends
    asset life, lowering future obligation generation rates."
    """
    if labor_type not in REGENERATIVE_PROFILES:
        raise KeyError(
            f"Unknown labor_type: {labor_type!r}. "
            f"Valid types: {list(REGENERATIVE_PROFILES.keys())}"
        )

    profile = REGENERATIVE_PROFILES[labor_type]

    # At higher ε, automated monitoring and precision tools extend the reach
    # of regenerative labor. Leverage grows modestly with automation.
    epsilon_leverage = 1.0 + REGEN_AUTOMATION_LEVERAGE_MAX * epsilon

    per_year = regenerative_hours * profile["eoh_saved_per_hour"] * epsilon_leverage
    amort    = profile["amortization_years"]
    lifetime = per_year * amort

    return {
        "labor_type":                    labor_type,
        "domain":                        profile["domain"],
        "description":                   profile["description"],
        "hours_worked":                  regenerative_hours,
        "current_eoh_fulfilled":         regenerative_hours,   # standard fulfillment
        "future_eoh_reduction_per_year": per_year,
        "amortization_years":            amort,
        "lifetime_eoh_savings":          lifetime,
        "epsilon_leverage":              epsilon_leverage,
    }


def regenerative_vs_maintenance_comparison(
    labor_hours: float,
    regen_type: str,
    current_eoh_demand: float,
    epsilon: float = 0.40,
) -> dict:
    """
    Compare the full impact of investing labor hours in regenerative vs. maintenance.

    Both modes create TEH (at the worker's multiplier rate). Regenerative labor
    additionally reduces future EOH obligations, which compounds over time.
    This comparison quantifies the long-term advantage of regenerative investment.

    Args:
        labor_hours: Hours of labor to compare.
        regen_type: Regenerative labor type (from REGENERATIVE_PROFILES).
        current_eoh_demand: Current EOH demand this labor would fulfill if
                            used for maintenance.
        epsilon: Automation level.

    Returns:
        dict with "maintenance" and "regenerative" sub-dicts, plus "net_advantage"
        showing the total EOH reduction advantage of the regenerative choice.

    Reference: Mission Statement §"Regenerative offset" — tracking the distinction
    "carries significant implications for long-term stewardship planning."
    """
    regen = regenerative_offset(regen_type, labor_hours, epsilon)

    maintenance_impact = {
        "current_eoh_fulfilled":     min(labor_hours, current_eoh_demand),
        "future_eoh_reduction":      0.0,
        "lifetime_eoh_impact":       min(labor_hours, current_eoh_demand),
    }

    regenerative_impact = {
        "current_eoh_fulfilled":     regen["current_eoh_fulfilled"],
        "future_eoh_reduction_per_year": regen["future_eoh_reduction_per_year"],
        "amortization_years":        regen["amortization_years"],
        "lifetime_eoh_impact":       (regen["current_eoh_fulfilled"]
                                      + regen["lifetime_eoh_savings"]),
    }

    net_advantage = (regenerative_impact["lifetime_eoh_impact"]
                     - maintenance_impact["lifetime_eoh_impact"])

    return {
        "maintenance":    maintenance_impact,
        "regenerative":   regenerative_impact,
        "net_advantage":  net_advantage,   # positive = regenerative wins long-term
        "epsilon":        epsilon,
    }


# ---------------------------------------------------------------------------
# Infrastructure Investment Logic
# ---------------------------------------------------------------------------

def eoh_reduction_ratio(
    production_cost_eoh: float,
    annual_maintenance_eoh: float,
    annual_eoh_eliminated: float,
    design_life: float,
    epsilon: float = 0.40,
) -> dict:
    """
    Research-only: investment analysis tool, not wired into dashboard or simulation.

    Used for off-line analysis of whether a specific asset's EOH reduction justifies
    its production and maintenance cost. Call from analytical scripts or test scenarios;
    do not call from dashboard.py or simulate_period() — investment ranking is not
    part of the period-by-period fiscal pipeline.

    Does this asset eliminate more system EOH than it costs to build and maintain?

    The production economy's core investment criterion: build what reduces
    aggregate EOH below its own lifetime cost. A factory is valuable not because
    it generates profit but because it reduces the total system entropy labor required.
    If a factory's infrastructure EOH (lifetime maintenance burden) exceeds the
    system EOH it eliminates, it is a net loss and should be written down
    (Mission Statement: production economy logic).

    Note: annual_eoh_eliminated reduces infrastructure/ecological/knowledge EOH
    at the system level. Personal EOH (biological needs) is not reduced by capital.

    At higher ε: automation handles an increasing share of the maintenance burden,
    so the effective maintenance cost in human-labor terms shrinks. This means
    an asset that appears marginal at ε=0 may become clearly worth building at ε=0.40.

    Args:
        production_cost_eoh: One-time EOH to build the asset (hours).
        annual_maintenance_eoh: Annual EOH to maintain the asset (hours/year).
        annual_eoh_eliminated: Annual system EOH (i/e/k domains) reduced by
                               this asset (hours/year) — piped water eliminates
                               ecological/infrastructure water-management burden.
        design_life: Asset's expected useful life (years).
        epsilon: Automation level. Scales the human-labor component of maintenance.

    Returns:
        dict: {
          "production_cost_eoh": float,
          "lifetime_maintenance_eoh": float,   (human-labor share only)
          "total_eoh_cost": float,             (production + maintenance)
          "lifetime_eoh_benefit": float,
          "net_eoh_reduction": float,          (benefit - cost; positive = good)
          "ratio": float,                      (<1.0 = net positive; >1.0 = net loss)
          "net_positive": bool,
          "payback_years": float | None,       (years until benefit exceeds cost)
          "epsilon": float,
        }

    Reference: Mission Statement §"Infrastructure EOH — the economic logic of
    infrastructure investment: build what generates less EOH than it eliminates";
    §"The production economy — A factory is valuable not because it generates
    profit but because it reduces the total human labor required to meet personal
    entropy obligations."
    """
    if design_life <= 0:
        raise ValueError(f"design_life must be positive, got {design_life}")
    if annual_eoh_eliminated < 0:
        raise ValueError("annual_eoh_eliminated cannot be negative")

    # At higher ε, automation handles more maintenance — human-labor share shrinks
    human_maint_fraction = 1.0 - epsilon
    lifetime_maint_human = annual_maintenance_eoh * design_life * human_maint_fraction

    # Production cost is incurred at ε=0 regardless (building requires human labor)
    # but scale by (1-ε) as well if automation assists construction
    effective_prod_cost = production_cost_eoh * (0.5 + 0.5 * (1.0 - epsilon))

    total_cost    = effective_prod_cost + lifetime_maint_human
    total_benefit = annual_eoh_eliminated * design_life

    ratio = total_cost / max(total_benefit, 1.0)
    net   = total_benefit - total_cost

    # Payback: years until cumulative benefit exceeds total cost
    if annual_eoh_eliminated > annual_maintenance_eoh * human_maint_fraction:
        annual_net = (annual_eoh_eliminated
                      - annual_maintenance_eoh * human_maint_fraction)
        payback_years = effective_prod_cost / annual_net if annual_net > 0 else None
    else:
        payback_years = None  # never pays back

    return {
        "production_cost_eoh":         effective_prod_cost,
        "lifetime_maintenance_eoh":    lifetime_maint_human,
        "total_eoh_cost":              total_cost,
        "lifetime_eoh_benefit":        total_benefit,
        "net_eoh_reduction":           net,
        "ratio":                       ratio,
        "net_positive":                ratio < 1.0,
        "payback_years":               payback_years,
        "epsilon":                     epsilon,
    }


def rank_investment_candidates(
    candidates: list[dict],
    epsilon: float = 0.40,
) -> list[dict]:
    """
    Research-only: investment ranking tool, not wired into dashboard or simulation.

    Rank infrastructure investment candidates by EOH reduction efficiency.

    Evaluates each candidate using eoh_reduction_ratio() and ranks by net EOH
    reduction per unit of production cost (highest return first). Candidates
    with ratio > 1.0 (net EOH loss) are flagged but still included so the
    caller can see the full landscape.

    Each candidate dict must contain:
        - "name": str
        - "production_cost_eoh": float
        - "annual_maintenance_eoh": float
        - "annual_eoh_eliminated": float
        - "design_life": float

    Args:
        candidates: List of proposed asset dicts.
        epsilon: Automation level (affects maintenance cost calculation).

    Returns:
        List of candidates enriched with eoh_reduction_ratio() results,
        sorted by net_eoh_reduction descending (best first).

    Reference: Mission Statement §"The production economy — build what maximizes
    net EOH reduction per unit of maintenance obligation."
    """
    results = []
    for c in candidates:
        analysis = eoh_reduction_ratio(
            production_cost_eoh=c["production_cost_eoh"],
            annual_maintenance_eoh=c["annual_maintenance_eoh"],
            annual_eoh_eliminated=c["annual_eoh_eliminated"],
            design_life=c["design_life"],
            epsilon=epsilon,
        )
        results.append({**c, **analysis})

    # Sort by net EOH reduction (highest first = most worth building)
    results.sort(key=lambda x: x["net_eoh_reduction"], reverse=True)
    return results


def optimal_investment(
    available_labor_eoh: float,
    candidates: list[dict],
    epsilon: float = 0.40,
) -> dict:
    """
    Research-only: investment allocation tool, not wired into dashboard or simulation.

    Greedily allocate available production-labor EOH to maximize net EOH reduction.

    Given a fixed budget of labor hours for capital investment, determines
    which assets to build in priority order. An asset is included if:
    1. It has a positive net_eoh_reduction (ratio < 1.0)
    2. Available labor covers its production_cost_eoh

    The greedy approach is appropriate here because EOH reduction benefits
    are roughly additive across independent assets.

    Args:
        available_labor_eoh: Labor hours available for capital investment.
        candidates: List of proposed asset dicts (same format as rank_investment_candidates).
        epsilon: Automation level.

    Returns:
        dict: {
          "funded": list[dict],            (assets to build, in priority order)
          "unfunded": list[dict],          (not built — insufficient labor or net-negative)
          "net_negative": list[dict],      (excluded: ratio > 1.0)
          "total_cost_eoh": float,
          "total_net_eoh_reduction": float,
          "labor_utilization": float,      (fraction of available_labor used)
          "remaining_labor": float,
        }

    Reference: Mission Statement §"The production economy — optimal_investment:
    where should the next hour of production labor go to maximize net EOH reduction?"
    """
    ranked = rank_investment_candidates(candidates, epsilon)

    # Separate net-positive from net-negative
    worthwhile = [r for r in ranked if r["net_positive"]]
    net_neg    = [r for r in ranked if not r["net_positive"]]

    funded   = []
    unfunded = []
    remaining = available_labor_eoh

    for asset in worthwhile:
        cost = asset["production_cost_eoh"]
        if cost <= remaining:
            funded.append(asset)
            remaining -= cost
        else:
            unfunded.append(asset)

    total_cost = sum(a["production_cost_eoh"] for a in funded)
    total_net  = sum(a["net_eoh_reduction"] for a in funded)

    return {
        "funded":                  funded,
        "unfunded":                unfunded,
        "net_negative":            net_neg,
        "total_cost_eoh":          total_cost,
        "total_net_eoh_reduction": total_net,
        "labor_utilization":       total_cost / max(available_labor_eoh, 1.0),
        "remaining_labor":         remaining,
    }


# ---------------------------------------------------------------------------
# Maintenance Strategy Comparison
# ---------------------------------------------------------------------------

def maintenance_strategy_compare(
    asset_type: str,
    annual_eoh: float,
    teh_value: float,
    initial_condition: float = 1.0,
    years_horizon: int = 30,
    epsilon: float = 0.40,
    natural_decay_rate: float = HUMAN_CAPITAL_NATURAL_DECAY,
    writedown_threshold: float = 0.20,
) -> dict:
    """
    Compare total human-labor EOH cost of three maintenance strategies over a
    time horizon, helping answer: is continuous maintenance cheaper than
    deferring until write-down or replacement?

    All costs use the human-labor share (1−ε) because automation handles the
    rest of the physical work. Both maintenance and rebuild scale down with
    automation, but the compounding EOH spike (from deferred neglect) is
    partially offset by better monitoring at high ε — making the comparison
    non-trivial and ε-dependent.

    Strategies:
    1. **continuous**: Pay annual_eoh × (1−ε) human-labor hours each year.
       Asset condition stays healthy; no write-down occurs in the horizon.
       Total = annual_eoh × (1−ε) × years_horizon.

    2. **deferred_to_writedown**: Pay no maintenance. Condition degrades per
       asset_condition_trajectory(fulfillment_fraction=0.0). When condition
       drops below writedown_threshold, a write-down fires: rebuild cost =
       teh_value × (1−ε) in human labor, plus compounding EOH from
       eoh_compounding(). After rebuild the asset runs on continuous
       maintenance for the remaining years.

    3. **replace_at_writedown**: Same deferred trajectory and trigger, but
       instead of rebuilding to same spec, the asset is replaced at 85% of
       rebuild cost (new-build with current technology; fewer custom fittings,
       better supply chain). Remaining years on continuous maintenance.

    At very high ε all three costs converge toward zero, but the compounding
    spike's ε-softening (eoh_compounding uses monitoring_softener) still
    differentiates strategies. Long-lived, threshold-sensitive assets (bridges,
    water systems) favor continuous maintenance; short-lived equipment at high
    ε may favor replacement.

    Args:
        asset_type: Key into ASSET_TYPES. Determines compound_exp and spike
                    factor used by eoh_compounding().
        annual_eoh: Annual maintenance EOH demand (hours/year) at full
                    human-labor level (ε=0 equivalent).
        teh_value: Asset's TEH value (proxy for rebuild cost at ε=0).
        initial_condition: Starting condition ∈ [0, 1]. Default: 1.0.
        years_horizon: Number of years over which to compare. Default: 30.
        epsilon: Automation level. Scales human-labor cost of all strategies.
        natural_decay_rate: Annual condition loss from unavoidable wear.
        writedown_threshold: Condition below which write-down triggers.
                             Default: 0.20 (matches writedown_trigger default).

    Returns:
        dict: {
          "asset_type":              str,
          "years_horizon":           int,
          "epsilon":                 float,
          "human_labor_fraction":    float,   (= 1 − ε)
          "continuous": {
            "total_eoh":             float,
            "annual_human_eoh":      float,
            "writedown_year":        None,
          },
          "deferred_to_writedown": {
            "total_eoh":             float,
            "writedown_year":        int | None,  (None if no writedown in horizon)
            "compounding_eoh":       float,
            "rebuild_eoh":           float,
          },
          "replace_at_writedown": {
            "total_eoh":             float,
            "writedown_year":        int | None,
            "replacement_eoh":       float,
          },
          "optimal_strategy":        str,    ("continuous" | "deferred_to_writedown"
                                              | "replace_at_writedown")
          "continuous_advantage":    float,  (deferred_total − continuous_total;
                                              positive = continuous cheaper)
        }

    Reference: Mission Statement §"Infrastructure EOH — the economic logic of
    infrastructure investment"; §"EOH and compounding — threshold-based, not
    exponential."
    """
    human_fraction = 1.0 - epsilon
    annual_human   = annual_eoh * human_fraction
    rebuild_eoh    = teh_value  * human_fraction
    replace_eoh    = rebuild_eoh * 0.85

    # --- Strategy 1: continuous ---
    continuous_total = annual_human * years_horizon

    # --- Strategies 2 & 3: deferred (shared condition projection) ---
    # Step condition forward one year at a time with zero fulfillment; stop as
    # soon as writedown triggers — avoids computing the full years_horizon list
    # when the threshold is hit early.
    neglect_period = [{"eoh_demanded": annual_eoh, "eoh_fulfilled": 0.0}]
    condition      = initial_condition
    writedown_year = None
    for yr in range(1, years_horizon + 1):
        condition = asset_condition(condition, neglect_period, natural_decay_rate)
        if writedown_trigger(condition, writedown_threshold):
            writedown_year = yr
            break

    if writedown_year is not None:
        # Compounding spike: physical EOH spike from years of neglect
        deferred_amount   = annual_eoh * writedown_year
        compounding_eoh   = eoh_compounding(deferred_amount, asset_type,
                                            float(writedown_year), epsilon)
        # Remaining years after rebuild/replace run on continuous maintenance
        post_writedown_yr = max(0, years_horizon - writedown_year)
        post_maint        = annual_human * post_writedown_yr

        # rebuild_eoh and replace_eoh already carry (1−ε) human fraction.
        # Compounding is physical; scale by human_fraction since automation
        # still handles a share of the crisis response.
        deferred_total = rebuild_eoh + compounding_eoh * human_fraction + post_maint
        replace_total  = replace_eoh + compounding_eoh * human_fraction + post_maint
    else:
        # No writedown within the horizon: deferred path costs 0 maintenance
        # (but note: this understates true long-term cost past the horizon).
        compounding_eoh = 0.0
        deferred_total  = 0.0
        replace_total   = 0.0

    if writedown_year is not None:
        totals  = {"continuous": continuous_total,
                   "deferred_to_writedown": deferred_total,
                   "replace_at_writedown":  replace_total}
        optimal = min(totals, key=lambda k: totals[k])
        # Positive = continuous cheaper; negative = a deferred strategy wins.
        # Uses the cheaper deferred option as the comparator.
        continuous_advantage: float | None = min(deferred_total, replace_total) - continuous_total
    else:
        # No writedown reached in the horizon: deferred strategies are
        # undercosted (0 maintenance, 0 rebuild within horizon). Only
        # continuous has complete-horizon data; do not compare.
        optimal = "continuous"
        continuous_advantage = None

    return {
        "asset_type":           asset_type,
        "years_horizon":        years_horizon,
        "epsilon":              epsilon,
        "human_labor_fraction": human_fraction,
        "continuous": {
            "total_eoh":        continuous_total,
            "annual_human_eoh": annual_human,
            "writedown_year":   None,
        },
        "deferred_to_writedown": {
            "total_eoh":       deferred_total,
            "writedown_year":  writedown_year,
            "compounding_eoh": compounding_eoh,
            "rebuild_eoh":     rebuild_eoh,
        },
        "replace_at_writedown": {
            "total_eoh":       replace_total,
            "writedown_year":  writedown_year,
            "replacement_eoh": replace_eoh,
        },
        "optimal_strategy":     optimal,
        "continuous_advantage": continuous_advantage,
    }


# ---------------------------------------------------------------------------
# Ecological deferred EOH paydown
# ---------------------------------------------------------------------------

def update_deferred_from_fulfillment(
    current_deferred: float,
    fulfilled_eoh: float,
) -> dict:
    """
    Reduce the deferred EOH backlog by the amount fulfilled this period.

    This closes the feedback loop between EOH fulfillment and the compounding
    model. Without this function, deferred EOH can only grow — assets fulfill
    EOH, but the backlog never shrinks. Calling this after each fulfillment
    event (asset elimination, regenerative labor, direct maintenance) keeps
    the deferred balance accurate for the next call to eoh_compounding().

    Semantics: fulfilled_eoh is the total EOH addressed this period (from
    annual_eoh_eliminated, future_eoh_reduction_per_year from regenerative
    labor, or direct maintenance hours × multiplier). It reduces the backlog
    up to but not beyond the current balance.

    Args:
        current_deferred: Current accumulated deferred EOH (hours). Non-negative.
        fulfilled_eoh: EOH fulfilled toward the backlog this period (hours).
                       Must be non-negative. Excess fulfillment is not carried
                       forward — it only reduces existing backlog.

    Returns:
        dict: {
          "previous_deferred": float,
          "fulfilled_eoh":     float,
          "reduction":         float,   (min(fulfilled_eoh, current_deferred))
          "new_deferred":      float,   (≥ 0; updated balance to store)
          "fully_cleared":     bool,    (True if backlog reaches zero)
          "excess_fulfillment": float,  (fulfilled beyond what was owed; usually 0)
        }

    Reference: Mission Statement §"The dual ledger — the gap between accumulated
    EOH and fulfilled EOH constitutes deferred maintenance; active investment
    must reduce that gap or compounding accelerates."
    """
    current_deferred = max(0.0, current_deferred)
    fulfilled_eoh    = max(0.0, fulfilled_eoh)

    reduction         = min(fulfilled_eoh, current_deferred)
    new_deferred      = current_deferred - reduction
    excess_fulfillment = fulfilled_eoh - reduction

    return {
        "previous_deferred":  current_deferred,
        "fulfilled_eoh":      fulfilled_eoh,
        "reduction":          reduction,
        "new_deferred":       new_deferred,
        "fully_cleared":      new_deferred <= 0.0,
        "excess_fulfillment": excess_fulfillment,
    }


def deferred_eoh_paydown(
    regenerative_result: dict,
    current_deferred: float,
) -> dict:
    """
    Retire accumulated deferred EOH through regenerative labor.

    regenerative_offset() computes how much future EOH a labor investment saves,
    but does not close the deferred backlog — that obligation is a one-way
    ratchet without this function. deferred_eoh_paydown() converts the
    regenerative result into an explicit paydown of the deferred balance,
    making active restoration visible in the ledger (Guardrail I).

    Semantics: the caller reduces their deferred balance (passed to
    ecological_eoh() or total_eoh()) by annual_paydown each year that
    regenerative labor is maintained.

    Args:
        regenerative_result: Return dict from regenerative_offset().
        current_deferred: Current accumulated deferred EOH balance (hours).

    Returns:
        dict: {
          "domain":                          str,
          "annual_paydown":                  float,  (per year; capped at current_deferred)
          "new_deferred_after_one_year":     float,
          "lifetime_paydown":                float,  (if maintained over full amortization period)
          "new_deferred_after_amortization": float,
          "deferred_cleared":                bool,   (one year's labor clears the entire backlog)
          "years_to_clear":                  float | None,  (None if balance is already zero)
        }

    Reference: Mission Statement §"Ecological EOH — the framework makes historical
    neglect visible; active restoration must reduce that visibility proportionally."
    """
    per_year = float(regenerative_result.get("future_eoh_reduction_per_year", 0.0))
    amort    = int(regenerative_result.get("amortization_years", 0))
    domain   = str(regenerative_result.get("domain", ""))

    annual_paydown = min(per_year, current_deferred)
    new_deferred_1 = max(0.0, current_deferred - annual_paydown)

    lifetime_paydown = min(per_year * amort, current_deferred)
    new_deferred_amort = max(0.0, current_deferred - lifetime_paydown)

    if current_deferred <= 0.0:
        years_to_clear = None
    elif per_year <= 0.0:
        years_to_clear = None
    else:
        years_to_clear = current_deferred / per_year

    return {
        "domain":                          domain,
        "annual_paydown":                  annual_paydown,
        "new_deferred_after_one_year":     new_deferred_1,
        "lifetime_paydown":                lifetime_paydown,
        "new_deferred_after_amortization": new_deferred_amort,
        "deferred_cleared":                annual_paydown >= current_deferred,
        "years_to_clear":                  years_to_clear,
    }


# ---------------------------------------------------------------------------
# Regenerative investment required (inverse of regenerative_offset)
# ---------------------------------------------------------------------------

def regenerative_investment_required(
    eoh_reduction_target: float,
    labor_type: str,
    epsilon: float = 0.40,
    years_horizon: int | None = None,
) -> dict:
    """
    Annual labor hours needed to achieve a target future EOH reduction rate.

    Inverts regenerative_offset(): given a desired future_eoh_reduction_per_year,
    computes hours_needed = target / (eoh_saved_per_hour × epsilon_leverage).
    This enables proactive workforce planning — "to reduce ecological EOH by
    50,000 h/yr, how much composting labor must we commit annually?"

    Args:
        eoh_reduction_target: Desired annual EOH reduction (hours/year).
        labor_type: Key into REGENERATIVE_PROFILES.
        epsilon: Automation level. Higher ε amplifies impact via epsilon_leverage.
        years_horizon: Override the profile's default amortization period for
                       the cumulative hours estimate. None → use profile default.

    Returns:
        dict: {
          "labor_type":                    str,
          "domain":                        str,
          "eoh_reduction_target_per_year": float,
          "hours_needed_per_year":         float,
          "cumulative_hours_over_horizon":  float,
          "years_horizon":                 int,
          "epsilon":                       float,
          "epsilon_leverage":              float,
        }

    Raises:
        KeyError: If labor_type is not in REGENERATIVE_PROFILES.

    Reference: Mission Statement §"Regenerative offset — some labor reduces
    future EOH rather than fulfilling current EOH."
    """
    if labor_type not in REGENERATIVE_PROFILES:
        raise KeyError(
            f"Unknown labor_type: {labor_type!r}. "
            f"Valid types: {list(REGENERATIVE_PROFILES.keys())}"
        )

    profile          = REGENERATIVE_PROFILES[labor_type]
    epsilon_leverage = 1.0 + REGEN_AUTOMATION_LEVERAGE_MAX * epsilon
    effective_rate   = profile["eoh_saved_per_hour"] * epsilon_leverage

    hours_needed     = eoh_reduction_target / max(effective_rate, 1e-10)
    horizon          = years_horizon if years_horizon is not None else profile["amortization_years"]
    cumulative_hours = hours_needed * horizon

    return {
        "labor_type":                    labor_type,
        "domain":                        profile["domain"],
        "eoh_reduction_target_per_year": eoh_reduction_target,
        "hours_needed_per_year":         hours_needed,
        "cumulative_hours_over_horizon":  cumulative_hours,
        "years_horizon":                 horizon,
        "epsilon":                       epsilon,
        "epsilon_leverage":              epsilon_leverage,
    }
