"""
The personal obligation: normative floor vs observed hours, and what separates them.

This is the reporting structure for a decomposition the repo cannot yet complete,
built so that the part it cannot do is visible instead of absorbed.

THE IDENTITY
------------
Observed time use is not the entropy obligation. It is

    observed  =  obligation  −  deferred  +  extraction

where `deferred` is obligation gone unserved (it shows up physiologically, never
in a diary) and `extraction` is institutionally-induced hours that resist no
entropy — commuting generated by settlement pattern, paperwork generated by the
administration of paperwork. One observable, three unknowns, so no amount of work
on the hours series alone separates them.

The normative floor breaks the deadlock from one side: a floor computed from
physical quantities at a stated delivery productivity is `obligation` by
construction, because nothing in it derives from what anyone was observed to do
or paid. That is the same move that closed the infrastructure determinacy gap
(doctrine spread 10.26× on the monetized path, 1.000× on the physical floor).

WHAT THIS MODULE REPORTS, AND WHAT IT REFUSES TO
--------------------------------------------------
The shipped basket prices ONE component of seven — 6.9% of the obligation by the
desk estimate's own weights. So the residual is not `extraction − deferred`; it is

    observed − floor_priced  =  floor_unpriced  −  deferred  +  extraction

— still three unknowns, now with the largest of them being the repo's own
incompleteness. `identity_report()` returns the residual under that name and
leaves `deferred` and `extraction` as None. It does not attribute.

This is deliberate and it is the finding: **the extraction wedge is not
identified at current basket coverage.** Raising coverage is the prerequisite for
quantifying it, and until then a number for extraction would be a fitted
residual wearing a theory's clothes — the floating-basket failure one level up.
An independent estimator (a cross-country frontier panel: the same physical
basket delivered in fewer hours elsewhere at comparable capital) is what would
identify it without a residual, and no such panel is ingested here.

Layer: scenarios/ imports core/ and reference/ — pure, no I/O beyond the shipped
reference extracts.

ε-coherence: `floor_arc()` exercises the floor at ε ∈ {0, 0.40, 0.99}. The floor
is ε-invariant in its priced components (a physical requirement does not depend
on the automation level) and a step function in which components have a delivery
path at all.

Reference: handoffs/personal_eoh/HANDOFF_personal_eoh_base.md §0.2, §2, §3.3;
notes/knowledge-eoh-closure.md Finding B.
"""

from __future__ import annotations

from typing import TypedDict

from hours_eoh.core.eoh_generation import PersonalFloor, personal_statutory_floor
from hours_eoh.data import (
    BASKET_DIET_KCAL_PER_DAY,
    BASKET_HEALTH_MIN_EPSILON,
    BASKET_SHELTER_M2_PER_PERSON,
    BASKET_THERMAL_DEGREE_DAYS_PER_YEAR,
    BASKET_WATER_LITRES_PER_DAY,
    PERSONAL_EOH_BASE,
    PERSONAL_EOH_SUFFICIENCY,
    PERSONAL_EOH_SURVIVAL,
)
from hours_eoh.reference import atus_time_use
from hours_eoh.reference.personal_basket import (
    CLIMATE_CONDITIONING,
    CLIMATE_NOTES,
    LSMS_AGRO_ECOLOGY,
    LSMS_COUNTRIES,
    NUTRITION_CROSSCHECK_HOURS_PER_YEAR,
    NUTRITION_TRANSFER_BIAS_SIGN,
    full_basket,
)


def shipped_basket() -> list[dict]:
    """The basket at the shipped quantities — the assembly point.

    `reference/personal_basket.py` holds the MEASURED delivery productivities and
    takes the CHOSEN quantities as arguments, so somebody has to bring the two
    halves together. That is this layer's job: `scenarios/` may import both
    `data.py` and `reference/`, and neither may import the other.
    """
    return full_basket(
        BASKET_DIET_KCAL_PER_DAY,
        BASKET_WATER_LITRES_PER_DAY,
        BASKET_THERMAL_DEGREE_DAYS_PER_YEAR,
        BASKET_SHELTER_M2_PER_PERSON,
        BASKET_HEALTH_MIN_EPSILON,
    )
from hours_eoh.scenarios.feasibility import age_weight_mean
# The US population the ATUS 15+ frame is bridged onto. Imported, not restated:
# two measured bridges onto the same denominator must be the same number.
from hours_eoh.scenarios.knowledge_base import REFERENCE_POPULATION_US

#: The counting conventions for "personal-domain labour", carried so the choice
#: is visible rather than buried. Every one is reported; the default is
#: `unpaid_core` — unpaid production for own household and others.
OBSERVED_CONVENTIONS: dict[str, tuple[str, ...]] = {
    # Household activities, caring for household members, caring for others.
    "unpaid_core": ("02", "03", "04"),
    # Adds provisioning and obtaining household services — the US analogue of
    # gathering — and volunteering.
    "unpaid_broad": ("02", "03", "04", "07", "09", "15"),
    # Paid work only. NOT additive with the above for a food-system total: the
    # conservation test needs food-system EMPLOYMENT, not all paid work.
    "paid": ("05",),
    # Everything counted as labour under either heading.
    "all_labour": ("02", "03", "04", "05"),
}


class IdentityReport(TypedDict):
    year: int
    epsilon: float
    convention: str
    observed_hours: float
    floor_priced: float
    coverage: float
    residual: float
    residual_terms: tuple[str, ...]
    deferred: None
    extraction: None
    identified: bool
    note: str


def obligation_floor(
    basket: list[dict] | None = None,
    epsilon: float = 0.0,
) -> PersonalFloor:
    """
    The task-normative personal obligation floor, in hours per person per year.

    Thin wrapper over `core.eoh_generation.personal_statutory_floor` supplying
    the shipped reference basket, so callers get the floor and its coverage
    together and cannot read one without the other.

    units: hours per person per year.

    ε-behavior: priced components are ε-invariant; `coverage` and `unreachable`
    are step functions of ε as step-in entitlements become deliverable.

    Worked example: at ε = 0 the shipped basket returns 330.9 h/person·yr at
    coverage 0.069 — crop production alone, with processing, water, shelter,
    thermal, sanitation and CARE unpriced and health below its step-in
    threshold. Care alone is 62.1% of the obligation, which is most of why the
    coverage is what it is.
    """
    return personal_statutory_floor(
        basket if basket is not None else shipped_basket(), epsilon
    )


def floor_arc(
    epsilons: tuple[float, ...] = (0.0, 0.40, 0.99),
    basket: list[dict] | None = None,
) -> list[PersonalFloor]:
    """The floor across the arc — the ε-coherence view of a physical requirement."""
    return [obligation_floor(basket, epsilon) for epsilon in epsilons]


def observed_hours(
    year: int | None = None,
    convention: str = "unpaid_core",
    total_population: float = REFERENCE_POPULATION_US,
) -> float:
    """
    Measured US hours per capita per year under a stated counting convention.

    units: hours per capita (ALL ages) per year — the unit EOH quantities use.

    Worked example: 2025, `unpaid_core` → 763.8 h/person·yr.

    Raises:
        KeyError: if the convention is not in `OBSERVED_CONVENTIONS`.
    """
    if convention not in OBSERVED_CONVENTIONS:
        raise KeyError(
            f"unknown convention {convention!r}; have {sorted(OBSERVED_CONVENTIONS)}"
        )
    year = atus_time_use.latest_year() if year is None else year
    return atus_time_use.hours_per_capita(
        year, OBSERVED_CONVENTIONS[convention], total_population
    )


def identity_report(
    year: int | None = None,
    epsilon: float = 0.0,
    convention: str = "unpaid_core",
    basket: list[dict] | None = None,
    total_population: float = REFERENCE_POPULATION_US,
) -> IdentityReport:
    """
    The three-term identity, with the unidentified terms left unidentified.

    Governing equation:

        observed − floor_priced  =  floor_unpriced − deferred + extraction

    `deferred` and `extraction` are returned as None, and `identified` is False,
    whenever basket coverage is below 1.0 — which is always, at present. The
    residual is reported under a name that lists what is in it.

    units: hours per capita per year.

    ε-behavior: `floor_priced` is ε-invariant in the shipped basket; the residual
    inherits that, so the whole report is meaningful at every ε.

    Worked example: 2025, ε = 0, unpaid_core → observed 763.8, floor_priced
    330.9 at coverage 0.069, residual 432.9 — of which the largest known term is
    the 93% of the basket nobody has costed, NOT extraction.
    """
    # Resolve the year ONCE: the year reported and the year measured must be the
    # same one, and two independent defaults are how they stop being.
    year = atus_time_use.latest_year() if year is None else year
    floor = obligation_floor(basket, epsilon)
    seen = observed_hours(year, convention, total_population)
    return IdentityReport(
        year=year,
        epsilon=epsilon,
        convention=convention,
        observed_hours=seen,
        floor_priced=floor["floor_hours"],
        coverage=floor["coverage"],
        residual=seen - floor["floor_hours"],
        residual_terms=("floor_unpriced", "deferred", "extraction"),
        deferred=None,
        extraction=None,
        identified=floor["coverage"] >= 1.0,
        note=(
            "residual = floor_unpriced − deferred + extraction. Three unknowns, "
            "not one. At coverage {:.2f} the residual is dominated by basket "
            "components nobody has costed; attributing it to extraction would be "
            "a fitted residual, not a measurement. Identification needs either "
            "full basket coverage or an independent frontier estimate."
        ).format(floor["coverage"]),
    )


def floor_vs_constants(epsilon: float = 0.0, basket: list[dict] | None = None) -> dict:
    """
    The floor against the constants it will eventually discipline — reporting only.

    Nothing here moves a constant. The comparison exists so the direction of
    travel is on the record: a floor that already exceeds a standard at partial
    coverage has falsified it, and a floor far below one has said nothing yet.

    `PERSONAL_EOH_SURVIVAL` and `PERSONAL_EOH_SUFFICIENCY` are quoted per
    working-age-EQUIVALENT; the floor and the ATUS observation are per capita.
    The `AGE_GROUPS` weight w = 1.475 bridges them, and it comes from
    `feasibility.age_weight_mean` rather than being recomputed here — forgetting
    it is the age-weight trap that module exists to catch, and two copies of the
    bridge is how the trap comes back.

    units: hours per capita per year throughout, after the w bridge.
    """
    weight = age_weight_mean()
    floor = obligation_floor(basket, epsilon)
    priced = floor["floor_hours"]
    # One list of standards; the shares are derived from it rather than restated,
    # so a fourth standard cannot be added to one half and forgotten in the other.
    per_capita = {
        name: value * weight
        for name, value in (
            ("PERSONAL_EOH_SURVIVAL", PERSONAL_EOH_SURVIVAL),
            ("PERSONAL_EOH_BASE", PERSONAL_EOH_BASE),
            ("PERSONAL_EOH_SUFFICIENCY", PERSONAL_EOH_SUFFICIENCY),
        )
    }
    return {
        "epsilon": epsilon,
        "age_weight": weight,
        "floor_priced_per_capita": priced,
        "coverage": floor["coverage"],
        "crosscheck_per_capita": NUTRITION_CROSSCHECK_HOURS_PER_YEAR,
        "constants_per_capita": per_capita,
        "floor_share_of": {
            name: priced / value for name, value in per_capita.items()
        },
        "verdict": (
            "the floor prices one component of seven — 6.9% of the obligation by "
            "the desk estimate's own weights — and falsifies nothing yet; it is a "
            "strict lower bound and the constants sit above it, which is the only "
            "ordering compatible with that coverage"
        ),
    }


def climate_conditioning(basket: list[dict] | None = None) -> dict:
    """
    Where latitude enters the floor, per component — the caveat that must travel
    with any figure this module returns.

    The basket's quantity / hours_per_unit split already separates what is OWED
    from what delivery COSTS, and climate lands almost entirely in the second.
    This reports which kind each component is, and flags the priced ones —
    because a costed component carries its measurement's climate with it, and an
    uncosted one does not yet carry anything.

    units: none — provenance, not a quantity.

    ε-behavior: none. Climate conditioning is a property of the measurement and
    of the physical requirement, not of the automation level.

    Worked example: at the shipped basket exactly one component is priced,
    `nutrition_production`, and it is `delivery`-conditioned — 331 h/person·yr is
    a rainfed tropical smallholder figure and does not transfer to a boreal
    collective without restratification. `transfer_bias_sign` is None because the
    direction is genuinely undetermined, not because it is unknown to the caller.
    """
    components = basket if basket is not None else shipped_basket()
    rows = []
    for component in components:
        name = component["component"]
        rows.append({
            "component": name,
            "priced": component["hours_per_unit"] is not None,
            "conditioning": CLIMATE_CONDITIONING.get(name, "unstated"),
            "note": CLIMATE_NOTES.get(name, ""),
        })
    priced_conditioned = [
        r["component"] for r in rows
        if r["priced"] and r["conditioning"] in ("delivery", "quantity_is_climate")
    ]
    return {
        "rows": rows,
        "agro_ecology_of_measurement": LSMS_AGRO_ECOLOGY,
        "countries": LSMS_COUNTRIES,
        "priced_and_climate_conditioned": priced_conditioned,
        "transfer_bias_sign": NUTRITION_TRANSFER_BIAS_SIGN,
        "verdict": (
            f"{len(priced_conditioned)} of the priced components carry their "
            f"measurement's climate. The floor is quotable for "
            f"{LSMS_AGRO_ECOLOGY.split(' — ')[0]} and is out of scope elsewhere "
            f"until restratified; the direction of the error is undetermined, so "
            f"it is not asserted."
        ),
    }
