"""
The personal obligation: normative floor vs observed hours, and what separates them.

This is the reporting structure for a decomposition the repo cannot yet complete,
built so that the part it cannot do is visible instead of absorbed.

THE IDENTITY
------------
Observed time use is not the entropy obligation. It is

    observed  =  obligation  −  deferred  +  extraction

where `deferred` is obligation gone unserved (it shows up physiologically, never
in a diary) and `extraction` is institutionally-induced hours that resist no
entropy — commuting generated by settlement pattern, paperwork generated by the
administration of paperwork. One observable, three unknowns, so no amount of work
on the hours series alone separates them.

The normative floor breaks the deadlock from one side: a floor computed from
physical quantities at a stated delivery productivity is `obligation` by
construction, because nothing in it derives from what anyone was observed to do
or paid. That is the same move that closed the infrastructure determinacy gap
(doctrine spread 10.26× on the monetized path, 1.000× on the physical floor).

WHAT THIS MODULE REPORTS, AND WHAT IT REFUSES TO
--------------------------------------------------
The shipped basket prices ONE component of seven — 6.9% of the obligation by the
desk estimate's own weights. So the residual is not `extraction − deferred`; it is

    observed − floor_priced  =  floor_unpriced  −  deferred  +  extraction

— still three unknowns, now with the largest of them being the repo's own
incompleteness. `identity_report()` returns the residual under that name and
leaves `deferred` and `extraction` as None. It does not attribute.

This is deliberate and it is the finding: **the extraction wedge is not
identified at current basket coverage.** Raising coverage is the prerequisite for
quantifying it, and until then a number for extraction would be a fitted
residual wearing a theory's clothes — the floating-basket failure one level up.
An independent estimator (a cross-country frontier panel: the same physical
basket delivered in fewer hours elsewhere at comparable capital) is what would
identify it without a residual, and no such panel is ingested here.

Layer: scenarios/ imports core/ and reference/ — pure, no I/O beyond the shipped
reference extracts.

ε-coherence: `floor_arc()` exercises the floor at ε ∈ {0, 0.40, 0.99}. The floor
is ε-invariant in its priced components (a physical requirement does not depend
on the automation level) and a step function in which components have a delivery
path at all.

Reference: the personal-obligation handoff §0.2, §2, §3.3;
the knowledge-base closure note Finding B.
"""

from __future__ import annotations

from typing import TypedDict

from hours_eoh.core.eoh_generation import PersonalFloor, personal_statutory_floor
from hours_eoh.data import (
    BASKET_WATER_CARRIED_FRACTION,
    BASKET_WATER_CARRY_LITRES,
    BASKET_WATER_DISTANCE_M,
    BASKET_WATER_LITRES_PER_DAY,
    WATER_WALKING_SPEED_M_S,
    CARE_CHILDCARE_HOURS_PER_PERSON_YEAR,
    BASKET_WATER_DISTANCE_M,
    BASKET_DIET_KCAL_PER_DAY,
    BASKET_HEALTH_MIN_EPSILON,
    BASKET_SHELTER_M2_PER_PERSON,
    BASKET_THERMAL_DEGREE_DAYS_PER_YEAR,
    BASKET_WATER_LITRES_PER_DAY,
    PERSONAL_EOH_BASE,
    PERSONAL_EOH_SUFFICIENCY,
    PERSONAL_EOH_SURVIVAL,
)
from hours_eoh.reference import atus_time_use
from hours_eoh.reference.personal_basket import (
    water_collection_hours,
    CLIMATE_CONDITIONING,
    CLIMATE_NOTES,
    LSMS_AGRO_ECOLOGY,
    LSMS_COUNTRIES,
    NUTRITION_CROSSCHECK_HOURS_PER_YEAR,
    NUTRITION_TRANSFER_BIAS_SIGN,
    full_basket,
)


def shipped_basket() -> list[dict]:
    """The basket at the shipped quantities — the assembly point.

    `reference/personal_basket.py` holds the MEASURED delivery productivities and
    takes the CHOSEN quantities as arguments, so somebody has to bring the two
    halves together. That is this layer's job: `scenarios/` may import both
    `data.py` and `reference/`, and neither may import the other.
    """
    return full_basket(
        BASKET_DIET_KCAL_PER_DAY,
        BASKET_WATER_LITRES_PER_DAY,
        BASKET_THERMAL_DEGREE_DAYS_PER_YEAR,
        BASKET_SHELTER_M2_PER_PERSON,
        BASKET_HEALTH_MIN_EPSILON,
        BASKET_WATER_DISTANCE_M,
        CARE_CHILDCARE_HOURS_PER_PERSON_YEAR,
    )
from hours_eoh.scenarios.feasibility import age_weight_mean, feasibility_check
# The US population the ATUS 15+ frame is bridged onto. Imported, not restated:
# two measured bridges onto the same denominator must be the same number.
from hours_eoh.scenarios.knowledge_base import REFERENCE_POPULATION_US

#: The counting conventions for "personal-domain labour", carried so the choice
#: is visible rather than buried. Every one is reported; the default is
#: `unpaid_core` — unpaid production for own household and others.
OBSERVED_CONVENTIONS: dict[str, tuple[str, ...]] = {
    # Household activities, caring for household members, caring for others.
    "unpaid_core": ("02", "03", "04"),
    # Adds provisioning and obtaining household services — the US analogue of
    # gathering — and volunteering.
    "unpaid_broad": ("02", "03", "04", "07", "09", "15"),
    # Paid work only. NOT additive with the above for a food-system total: the
    # conservation test needs food-system EMPLOYMENT, not all paid work.
    "paid": ("05",),
    # Everything counted as labour under either heading.
    "all_labour": ("02", "03", "04", "05"),
}


class IdentityReport(TypedDict):
    year: int
    epsilon: float
    convention: str
    observed_hours: float
    floor_priced: float
    coverage: float
    residual: float
    residual_terms: tuple[str, ...]
    deferred: None
    extraction: None
    identified: bool
    note: str


def obligation_floor(
    basket: list[dict] | None = None,
    epsilon: float = 0.0,
) -> PersonalFloor:
    """
    The task-normative personal obligation floor, in hours per person per year.

    Thin wrapper over `core.eoh_generation.personal_statutory_floor` supplying
    the shipped reference basket, so callers get the floor and its coverage
    together and cannot read one without the other.

    units: hours per person per year.

    ε-behavior: priced components are ε-invariant; `coverage` and `unreachable`
    are step functions of ε as step-in entitlements become deliverable.

    SHAPE, not levels: the floor is a PARTIAL construction and `coverage` says
    how partial. **The levels are not restated here** — pricing care and
    processing moved coverage by an order of magnitude (0.069 → 0.759) within a
    day, and a docstring figure cannot track that. Run the function. What
    remains unreachable is reported by name in `unreachable`, with the reason,
    rather than folded into the number.
    """
    return personal_statutory_floor(
        basket if basket is not None else shipped_basket(), epsilon
    )


def floor_arc(
    epsilons: tuple[float, ...] = (0.0, 0.40, 0.99),
    basket: list[dict] | None = None,
) -> list[PersonalFloor]:
    """The floor across the arc — the ε-coherence view of a physical requirement."""
    return [obligation_floor(basket, epsilon) for epsilon in epsilons]


def observed_hours(
    year: int | None = None,
    convention: str = "unpaid_core",
    total_population: float = REFERENCE_POPULATION_US,
) -> float:
    """
    Measured US hours per capita per year under a stated counting convention.

    units: hours per capita (ALL ages) per year — the unit EOH quantities use.

    Worked example: 2025, `unpaid_core` → 763.8 h/person·yr.

    Raises:
        KeyError: if the convention is not in `OBSERVED_CONVENTIONS`.
    """
    if convention not in OBSERVED_CONVENTIONS:
        raise KeyError(
            f"unknown convention {convention!r}; have {sorted(OBSERVED_CONVENTIONS)}"
        )
    year = atus_time_use.latest_year() if year is None else year
    return atus_time_use.hours_per_capita(
        year, OBSERVED_CONVENTIONS[convention], total_population
    )


def identity_report(
    year: int | None = None,
    epsilon: float = 0.0,
    convention: str = "unpaid_core",
    basket: list[dict] | None = None,
    total_population: float = REFERENCE_POPULATION_US,
) -> IdentityReport:
    """
    The three-term identity, with the unidentified terms left unidentified.

    Governing equation:

        observed − floor_priced  =  floor_unpriced − deferred + extraction

    `deferred` and `extraction` are returned as None, and `identified` is False,
    whenever basket coverage is below 1.0 — which is always, at present. The
    residual is reported under a name that lists what is in it.

    units: hours per capita per year.

    ε-behavior: `floor_priced` is ε-invariant in the shipped basket; the residual
    inherits that, so the whole report is meaningful at every ε.

    SHAPE: the residual is dominated by the share of the basket nobody has
    costed, NOT by extraction. **The levels are deliberately not written out** —
    they moved with the care and processing pricing and the previous
    restatement here went stale by a factor of eleven on coverage.
    """
    # Resolve the year ONCE: the year reported and the year measured must be the
    # same one, and two independent defaults are how they stop being.
    year = atus_time_use.latest_year() if year is None else year
    floor = obligation_floor(basket, epsilon)
    seen = observed_hours(year, convention, total_population)
    return IdentityReport(
        year=year,
        epsilon=epsilon,
        convention=convention,
        observed_hours=seen,
        floor_priced=floor["floor_hours"],
        coverage=floor["coverage"],
        residual=seen - floor["floor_hours"],
        residual_terms=("floor_unpriced", "deferred", "extraction"),
        deferred=None,
        extraction=None,
        identified=floor["coverage"] >= 1.0,
        note=(
            "residual = floor_unpriced − deferred + extraction. Three unknowns, "
            "not one. At coverage {:.2f} the residual is dominated by basket "
            "components nobody has costed; attributing it to extraction would be "
            "a fitted residual, not a measurement. Identification needs either "
            "full basket coverage or an independent frontier estimate."
        ).format(floor["coverage"]),
    )


def floor_vs_constants(epsilon: float = 0.0, basket: list[dict] | None = None) -> dict:
    """
    The floor against the constants it will eventually discipline — reporting only.

    Nothing here moves a constant. The comparison exists so the direction of
    travel is on the record: a floor that already exceeds a standard at partial
    coverage has falsified it, and a floor far below one has said nothing yet.

    `PERSONAL_EOH_SURVIVAL` and `PERSONAL_EOH_SUFFICIENCY` are quoted per
    working-age-EQUIVALENT; the floor and the ATUS observation are per capita.
    The `AGE_GROUPS` weight w = 1.475 bridges them, and it comes from
    `feasibility.age_weight_mean` rather than being recomputed here — forgetting
    it is the age-weight trap that module exists to catch, and two copies of the
    bridge is how the trap comes back.

    units: hours per capita per year throughout, after the w bridge.
    """
    weight = age_weight_mean()
    floor = obligation_floor(basket, epsilon)
    priced = floor["floor_hours"]
    # One list of standards; the shares are derived from it rather than restated,
    # so a fourth standard cannot be added to one half and forgotten in the other.
    per_capita = {
        name: value * weight
        for name, value in (
            ("PERSONAL_EOH_SURVIVAL", PERSONAL_EOH_SURVIVAL),
            ("PERSONAL_EOH_BASE", PERSONAL_EOH_BASE),
            ("PERSONAL_EOH_SUFFICIENCY", PERSONAL_EOH_SUFFICIENCY),
        )
    }
    return {
        "epsilon": epsilon,
        "age_weight": weight,
        "floor_priced_per_capita": priced,
        "coverage": floor["coverage"],
        "crosscheck_per_capita": NUTRITION_CROSSCHECK_HOURS_PER_YEAR,
        "constants_per_capita": per_capita,
        # SCOPED: each standard is compared against the components it is about,
        # not against the whole basket. See `_STANDARD_SCOPE`.
        "floor_share_of": {
            name: _scoped_floor(floor, name) / value
            for name, value in per_capita.items()
        },
        "floor_scoped_to": {
            name: _scoped_floor(floor, name) for name in per_capita
        },
        # WHAT THE UNPRICED REMAINDER WOULD HAVE TO DELIVER, per unit of desk
        # share, for PERSONAL_EOH_BASE to be right. This is the first thing the
        # floor has been able to say ABOUT the base rather than merely sitting
        # under it: the priced components deliver an observed intensity, and the
        # rest must clear the gap out of the share that is left.
        "remainder_intensity_ratio": _remainder_intensity_ratio(
            priced, floor["coverage"], per_capita["PERSONAL_EOH_BASE"]),
        "verdict": _floor_verdict(floor, priced, per_capita),
    }


#: WHICH COMPONENTS EACH STANDARD IS SCOPED TO. Added 2026-09-10 after the
#: comparison produced a FALSE POSITIVE: the whole-basket floor crossed
#: `PERSONAL_EOH_SURVIVAL` and the verdict reported a falsification, when the
#: exceedance was entirely the care term and that standard's own `resolves_by`
#: reads "only the components that kill you if unmet — food, water, shelter,
#: warmth". Care is not in it.
#:
#: The mismatch is OLDER than the crossing — `floor_share_of` has always divided
#: the whole floor by every constant — and was invisible only while the floor was
#: too small to reach any of them. That is the shape this repo calls measuring
#: where the defect cannot be seen: the check could not have failed, so its
#: passing meant nothing, and its first real firing was wrong.
#:
#: None means the standard covers the whole basket.
_STANDARD_SCOPE: dict[str, tuple[str, ...] | None] = {
    "PERSONAL_EOH_SURVIVAL": (
        "nutrition_production", "nutrition_processing", "water", "shelter",
    ),
    "PERSONAL_EOH_BASE": None,
    "PERSONAL_EOH_SUFFICIENCY": None,
}


def _scoped_floor(floor: PersonalFloor, standard: str) -> float:
    """The part of the priced floor a given standard is actually about."""
    scope = _STANDARD_SCOPE.get(standard)
    if scope is None:
        return sum(floor["by_component"].values())
    return sum(v for k, v in floor["by_component"].items() if k in scope)


def _remainder_intensity_ratio(
    priced: float, coverage: float, base_per_capita: float
) -> float | None:
    """
    (hours per unit share the REMAINDER must deliver) / (what the priced part did).

    None when nothing is priced or everything is, where the ratio has no content.
    """
    if coverage <= 0.0 or coverage >= 1.0 or priced <= 0.0:
        return None
    gap = base_per_capita - priced
    if gap <= 0.0:
        return None
    return (gap / (1.0 - coverage)) / (priced / coverage)


def _floor_verdict(
    floor: PersonalFloor, priced: float, per_capita: dict[str, float]
) -> str:
    """
    COMPUTED, not restated. The previous version of this string said "one
    component of seven — 6.9%" as a literal, and went stale the moment a second
    component was priced — the drift this repo has caught more often than any
    other, on the function whose whole job is to report where the floor stands.
    """
    total = len(floor["by_component"]) + len(floor["unreachable"])
    n = len(floor["by_component"])
    cov = floor["coverage"]
    # SCOPE-AWARE. Comparing the whole floor against a standard scoped to a
    # subset is what produced a false falsification on 2026-09-10.
    exceeded = [k for k, v in per_capita.items() if _scoped_floor(floor, k) > v]
    if exceeded:
        return (
            f"the floor prices {n} of {total} components ({cov:.1%} of the "
            f"obligation by the desk estimate's own weights) and EXCEEDS "
            f"{', '.join(sorted(exceeded))} — it is a strict lower bound, so "
            "exceeding a standard falsifies it rather than merely disagreeing"
        )
    ratio = _remainder_intensity_ratio(priced, cov, per_capita["PERSONAL_EOH_BASE"])
    tail = (
        f" For PERSONAL_EOH_BASE to be right the unpriced {1 - cov:.1%} of share "
        f"must deliver {ratio:.1f}x the hours per unit share that the priced part "
        "did." if ratio else ""
    )
    return (
        f"the floor prices {n} of {total} components ({cov:.1%} of the obligation "
        "by the desk estimate's own weights) and falsifies nothing yet; it is a "
        "strict lower bound and the constants sit above it." + tail
    )


def climate_conditioning(basket: list[dict] | None = None) -> dict:
    """
    Where latitude enters the floor, per component — the caveat that must travel
    with any figure this module returns.

    The basket's quantity / hours_per_unit split already separates what is OWED
    from what delivery COSTS, and climate lands almost entirely in the second.
    This reports which kind each component is, and flags the priced ones —
    because a costed component carries its measurement's climate with it, and an
    uncosted one does not yet carry anything.

    units: none — provenance, not a quantity.

    ε-behavior: none. Climate conditioning is a property of the measurement and
    of the physical requirement, not of the automation level.

    Worked example: at the shipped basket exactly one component is priced,
    `nutrition_production`, and it is `delivery`-conditioned — 331 h/person·yr is
    a rainfed tropical smallholder figure and does not transfer to a boreal
    collective without restratification. `transfer_bias_sign` is None because the
    direction is genuinely undetermined, not because it is unknown to the caller.
    """
    components = basket if basket is not None else shipped_basket()
    rows = []
    for component in components:
        name = component["component"]
        rows.append({
            "component": name,
            "priced": component["hours_per_unit"] is not None,
            "conditioning": CLIMATE_CONDITIONING.get(name, "unstated"),
            "note": CLIMATE_NOTES.get(name, ""),
        })
    priced_conditioned = [
        r["component"] for r in rows
        if r["priced"] and r["conditioning"] in ("delivery", "quantity_is_climate")
    ]
    return {
        "rows": rows,
        "agro_ecology_of_measurement": LSMS_AGRO_ECOLOGY,
        "countries": LSMS_COUNTRIES,
        "priced_and_climate_conditioned": priced_conditioned,
        "transfer_bias_sign": NUTRITION_TRANSFER_BIAS_SIGN,
        "verdict": (
            f"{len(priced_conditioned)} of the priced components carry their "
            f"measurement's climate. The floor is quotable for "
            f"{LSMS_AGRO_ECOLOGY.split(' — ')[0]} and is out of scope elsewhere "
            f"until restratified; the direction of the error is undetermined, so "
            f"it is not asserted."
        ),
    }


def water_feasibility(
    distance_m: float = BASKET_WATER_DISTANCE_M,
    carry_litres: float = BASKET_WATER_CARRY_LITRES,
    carried_fraction: float = BASKET_WATER_CARRIED_FRACTION,
    litres_per_day: float = BASKET_WATER_LITRES_PER_DAY,
    walking_speed_m_s: float = WATER_WALKING_SPEED_M_S,
    epsilon: float = 0.0,
) -> dict:
    """
    Does the declared water collection fit the labour the population has?

    units: hours per person per year, and shares of the obligation.

    **THE SAME MOVE AS THE REGISTER CADENCE, AND FOR THE SAME REASON.** Water
    was blocked on an acquisition — DHS water-collection time for ~90 countries
    — that the repo's own `COMPONENT_STATUS` already said would not settle it:
    *"A FORM QUESTION FIRST, THEN AN ACQUISITION, and the form question is why
    DHS would not have settled it."* Four independent variables sit inside one
    hours-per-litre, each spanning an order of magnitude, so a measured central
    value describes no actual collective and transfers nowhere.

    So the framework does not measure water. **It supplies the BOUND and the
    collective declares its position** — distance, carry, carried fraction —
    exactly as it declares its population, its land and its register cadence.
    The only universal in the chain is walking speed, which is physics.

    **WHAT THE BOUND IS.** `feasibility_check` already tests demand against the
    labour supply; water enters as demand like any other obligation. This
    reports the declared collection cost, what it leaves, and the DISTANCE at
    which the configuration stops clearing — solved rather than swept, because
    distance is the variable a collective least controls and most needs bounded.

    **THE DEFAULTS ERR HIGH AND ARE NOT A CENTRAL ESTIMATE.**
    `BASKET_WATER_CARRIED_FRACTION` ships at 1.0 — ALL water carried home, the
    conservative corner — and the distance default is explicitly a stand-in
    that is never multiplied into the floor. A collective that washes at the
    source, or pipes, declares less and the term shrinks or vanishes.
    """
    water = water_collection_hours(
        distance_m, carry_litres, carried_fraction,
        litres_per_day, walking_speed_m_s,
    )
    hours = water["hours_per_person_year"]

    base = feasibility_check(epsilon=epsilon)
    supply = base["supply_per_capita"]
    demand = base["total_demand_per_capita"]
    headroom = max(0.0, supply - demand)

    # The distance at which this declaration stops clearing. Linear in distance
    # at fixed carry and fraction, so it inverts exactly rather than bisecting.
    per_metre = (hours / distance_m) if distance_m > 0.0 else (
        water_collection_hours(1.0, carry_litres, carried_fraction,
                               litres_per_day, walking_speed_m_s
                               )["hours_per_person_year"]
    )
    max_distance = (headroom / per_metre) if per_metre > 0.0 else None

    return {
        "epsilon":                  epsilon,
        "declared":                 water["declared"],
        "hours_per_person_year":    hours,
        "share_of_obligation":      hours / demand if demand > 0 else None,
        "labour_headroom_h":        headroom,
        "fits":                     hours <= headroom,
        "max_distance_m_that_clears": max_distance,
        "is_measured":              False,
        "note": (
            "The framework supplies the bound; the collective declares its "
            "position. Nothing here measures YOUR water, and a figure measured "
            "for another population would not transfer - the form spans 60x "
            "across plausible declarations."
        ),
    }
