"""
Generate the per-entry index at the top of each `record/<area>.md` history.

WHY THIS EXISTS. `record/` holds 85 entries across nine area files, 89% of the
bytes being history. History is the evidence that makes the failure modes in
CLAUDE.md believable and the detail to reach for when one fires — so it must
NOT be capped. But a file nobody can navigate prevents no repeats, however
complete it is. The quantity to bound is the cost of ONE retrieval, and an index
bounds it without deleting anything: a reader jumps to an anchor instead of
scanning 50k of prose.

WHAT IT DOES NOT DO. It does not summarise, rank or judge an entry — the row is
the entry's own bold lead, truncated. Anything cleverer would be a second
account of the entry (corpus F-008) and would go stale against it.

Usage:
    python3 utils/record_index.py            # print the size report
    python3 utils/record_index.py --write    # regenerate every index
    python3 utils/record_index.py --check    # exit 1 if any index is stale
"""

from __future__ import annotations

import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
RECORD_DIR = REPO_ROOT / "record"

BEGIN = "<!-- record-index: generated by utils/record_index.py, do not hand-edit -->"
END = "<!-- /record-index -->"

#: The anchor that opens an entry, and the bold lead that follows it.
_ENTRY = re.compile(r'<a id="([^"]+)"></a>\s*\n\s*\n\*\*(.+?)\*\*', re.S)
_REGION = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)

#: A live surface is a summary; past this it is a second history. Nine files
#: written independently landed in 4,058–4,996 with no coordination, so this
#: codifies a regularity rather than imposing one. It binds on nothing today,
#: which is the point — it catches the regression, not the present.
LIVE_SURFACE_MAX = 6_000

HEADLINE_MAX = 96


def area_files() -> list[pathlib.Path]:
    return sorted(p for p in RECORD_DIR.glob("*.md") if p.name != "README.md")


def is_stub(text: str) -> bool:
    return "## MIGRATION STATUS — not yet migrated" in text


def split_history(text: str) -> tuple[str, str]:
    """`(everything before '## History', the history body)`."""
    head, sep, hist = text.partition("## History\n")
    return (head + sep, hist) if sep else (text, "")


def entries(history: str) -> list[tuple[str, str]]:
    """`(anchor, headline)` for each entry, in file order."""
    out = []
    for m in _ENTRY.finditer(history):
        lead = " ".join(m.group(2).split())
        if len(lead) > HEADLINE_MAX:
            lead = lead[: HEADLINE_MAX - 1].rstrip() + "…"
        out.append((m.group(1), lead))
    return out


def render(rows: list[tuple[str, str]]) -> str:
    if not rows:
        return f"{BEGIN}\n\n_No entries yet._\n\n{END}"
    body = "\n".join(f"| [{a}](#{a}) | {h} |" for a, h in rows)
    return (f"{BEGIN}\n\n"
            f"| {len(rows)} entries, newest first | |\n|---|---|\n{body}\n\n"
            f"{END}")


def rebuilt(text: str) -> str:
    """`text` with its index regenerated, inserted if absent."""
    head, hist = split_history(text)
    if not hist:
        return text
    block = render(entries(hist))
    if _REGION.search(hist):
        return head + _REGION.sub(lambda _: block, hist, count=1)
    return head + "\n" + block + "\n" + hist.lstrip("\n")


def report() -> list[tuple[str, int, int, int]]:
    """`(name, live surface, history, entry count)` per migrated area file."""
    rows = []
    for p in area_files():
        text = p.read_text(encoding="utf-8")
        if is_stub(text):
            continue
        head, hist = split_history(text)
        rows.append((p.name, len(head), len(hist), len(entries(hist))))
    return rows


def main() -> int:
    rows = report()

    if "--write" in sys.argv:
        for p in area_files():
            text = p.read_text(encoding="utf-8")
            if is_stub(text):
                continue
            new = rebuilt(text)
            if new != text:
                p.write_text(new, encoding="utf-8")
                print(f"wrote index: {p.name}")
        rows = report()

    if "--check" in sys.argv:
        stale = [p.name for p in area_files()
                 if not is_stub(t := p.read_text(encoding="utf-8")) and rebuilt(t) != t]
        for name in stale:
            print(f"FAIL {name}: index is stale — rerun with --write", file=sys.stderr)
        if stale:
            return 1

    # REPORTING ONLY — no ceiling, deliberately. History is the evidence that
    # stops a defect being rediscovered; capping it would trade a known cost
    # (a large read) for an unknown one (a lesson nobody can reach).
    print(f"\n{'file':22} {'live':>7} {'history':>9} {'entries':>8}")
    for name, live, hist, n in rows:
        flag = "  <-- live surface over budget" if live > LIVE_SURFACE_MAX else ""
        print(f"{name:22} {live:>7,} {hist:>9,} {n:>8}{flag}")
    tl, th, te = (sum(r[i] for r in rows) for i in (1, 2, 3))
    print(f"{'TOTAL':22} {tl:>7,} {th:>9,} {te:>8}")
    print(f"\nlive surface is {100 * tl / (tl + th):.1f}% of record/; "
          f"budget {LIVE_SURFACE_MAX:,}/file, history unbounded by design")
    return 0


if __name__ == "__main__":
    sys.exit(main())
